name: native_camera_example
description: Demonstrates how to use the native_camera plugin.
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  path_provider: ^1.6.11
  permission_handler: ^5.0.1
  native_camera:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true