// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AspectRatio;
@class CameraInfo;
@class CameraState;
@class Range;
@class Size_Class;
GPB_ENUM_FWD_DECLARE(CameraState_Orientation);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NativeCameraRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NativeCameraRoot : GPBRootObject
@end

#pragma mark - InitializeCameraRequest

typedef GPB_ENUM(InitializeCameraRequest_FieldNumber) {
  InitializeCameraRequest_FieldNumber_ChannelName = 1,
  InitializeCameraRequest_FieldNumber_State = 2,
};

GPB_FINAL @interface InitializeCameraRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;

@property(nonatomic, readwrite, strong, null_resettable) CameraState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@end

#pragma mark - InitializeCameraResponse

typedef GPB_ENUM(InitializeCameraResponse_FieldNumber) {
  InitializeCameraResponse_FieldNumber_TextureId = 1,
  InitializeCameraResponse_FieldNumber_State = 2,
  InitializeCameraResponse_FieldNumber_Orientation = 3,
  InitializeCameraResponse_FieldNumber_PreviewSize = 4,
  InitializeCameraResponse_FieldNumber_SupportedRatioArray = 5,
  InitializeCameraResponse_FieldNumber_SupportedPreviewFpsArray = 6,
};

GPB_FINAL @interface InitializeCameraResponse : GPBMessage

@property(nonatomic, readwrite) int64_t textureId;

@property(nonatomic, readwrite, strong, null_resettable) CameraState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@property(nonatomic, readwrite) enum CameraState_Orientation orientation;

@property(nonatomic, readwrite, strong, null_resettable) Size_Class *previewSize;
/** Test to see if @c previewSize has been set. */
@property(nonatomic, readwrite) BOOL hasPreviewSize;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AspectRatio*> *supportedRatioArray;
/** The number of items in @c supportedRatioArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger supportedRatioArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Range*> *supportedPreviewFpsArray;
/** The number of items in @c supportedPreviewFpsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger supportedPreviewFpsArray_Count;

@end

/**
 * Fetches the raw value of a @c InitializeCameraResponse's @c orientation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t InitializeCameraResponse_Orientation_RawValue(InitializeCameraResponse *message);
/**
 * Sets the raw value of an @c InitializeCameraResponse's @c orientation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetInitializeCameraResponse_Orientation_RawValue(InitializeCameraResponse *message, int32_t value);

#pragma mark - ListCamerasResponse

typedef GPB_ENUM(ListCamerasResponse_FieldNumber) {
  ListCamerasResponse_FieldNumber_CamerasArray = 1,
};

GPB_FINAL @interface ListCamerasResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CameraInfo*> *camerasArray;
/** The number of items in @c camerasArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger camerasArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
