// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CameraInfo;
@class CameraState;
GPB_ENUM_FWD_DECLARE(CameraState_Orientation);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NativeCameraRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NativeCameraRoot : GPBRootObject
@end

#pragma mark - InitializeCameraRequest

typedef GPB_ENUM(InitializeCameraRequest_FieldNumber) {
  InitializeCameraRequest_FieldNumber_ChannelName = 1,
  InitializeCameraRequest_FieldNumber_State = 2,
};

GPB_FINAL @interface InitializeCameraRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;

@property(nonatomic, readwrite, strong, null_resettable) CameraState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@end

#pragma mark - InitializeCameraResponse

typedef GPB_ENUM(InitializeCameraResponse_FieldNumber) {
  InitializeCameraResponse_FieldNumber_TextureId = 1,
  InitializeCameraResponse_FieldNumber_State = 2,
};

GPB_FINAL @interface InitializeCameraResponse : GPBMessage

@property(nonatomic, readwrite) int64_t textureId;

@property(nonatomic, readwrite, strong, null_resettable) CameraState *state;
/** Test to see if @c state has been set. */
@property(nonatomic, readwrite) BOOL hasState;

@end

#pragma mark - ListCamerasResponse

typedef GPB_ENUM(ListCamerasResponse_FieldNumber) {
  ListCamerasResponse_FieldNumber_CamerasArray = 1,
};

GPB_FINAL @interface ListCamerasResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CameraInfo*> *camerasArray;
/** The number of items in @c camerasArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger camerasArray_Count;

@end

#pragma mark - TakePictureRequest

typedef GPB_ENUM(TakePictureRequest_FieldNumber) {
  TakePictureRequest_FieldNumber_Path = 1,
  TakePictureRequest_FieldNumber_Exif = 2,
  TakePictureRequest_FieldNumber_WriteExif = 3,
  TakePictureRequest_FieldNumber_Quality = 4,
  TakePictureRequest_FieldNumber_PauseAfterCapture = 5,
  TakePictureRequest_FieldNumber_FixOrientation = 6,
  TakePictureRequest_FieldNumber_ForceUpOrientation = 7,
  TakePictureRequest_FieldNumber_Width = 8,
  TakePictureRequest_FieldNumber_MirrorImage = 9,
  TakePictureRequest_FieldNumber_DoNotSave = 10,
  TakePictureRequest_FieldNumber_ReturnBytes = 11,
  TakePictureRequest_FieldNumber_Orientation = 12,
};

GPB_FINAL @interface TakePictureRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *exif;
/** The number of items in @c exif without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger exif_Count;

/** Should write exif to file */
@property(nonatomic, readwrite) BOOL writeExif;

/** Value between 0-1 */
@property(nonatomic, readwrite) double quality;

@property(nonatomic, readwrite) BOOL pauseAfterCapture;

/** only used on Android */
@property(nonatomic, readwrite) BOOL fixOrientation;

/** only used on iOS */
@property(nonatomic, readwrite) BOOL forceUpOrientation;

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) BOOL mirrorImage;

@property(nonatomic, readwrite) BOOL doNotSave;

@property(nonatomic, readwrite) BOOL returnBytes;

@property(nonatomic, readwrite) enum CameraState_Orientation orientation;

@end

/**
 * Fetches the raw value of a @c TakePictureRequest's @c orientation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TakePictureRequest_Orientation_RawValue(TakePictureRequest *message);
/**
 * Sets the raw value of an @c TakePictureRequest's @c orientation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTakePictureRequest_Orientation_RawValue(TakePictureRequest *message, int32_t value);

#pragma mark - TakePictureResponse

typedef GPB_ENUM(TakePictureResponse_FieldNumber) {
  TakePictureResponse_FieldNumber_DeviceOrientation = 1,
  TakePictureResponse_FieldNumber_PictureOrientation = 2,
  TakePictureResponse_FieldNumber_Exif = 3,
  TakePictureResponse_FieldNumber_Width = 4,
  TakePictureResponse_FieldNumber_Height = 5,
  TakePictureResponse_FieldNumber_Uri = 6,
  TakePictureResponse_FieldNumber_Data_p = 7,
};

GPB_FINAL @interface TakePictureResponse : GPBMessage

@property(nonatomic, readwrite) enum CameraState_Orientation deviceOrientation;

@property(nonatomic, readwrite) enum CameraState_Orientation pictureOrientation;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *exif;
/** The number of items in @c exif without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger exif_Count;

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

/**
 * Fetches the raw value of a @c TakePictureResponse's @c deviceOrientation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TakePictureResponse_DeviceOrientation_RawValue(TakePictureResponse *message);
/**
 * Sets the raw value of an @c TakePictureResponse's @c deviceOrientation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTakePictureResponse_DeviceOrientation_RawValue(TakePictureResponse *message, int32_t value);

/**
 * Fetches the raw value of a @c TakePictureResponse's @c pictureOrientation property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TakePictureResponse_PictureOrientation_RawValue(TakePictureResponse *message);
/**
 * Sets the raw value of an @c TakePictureResponse's @c pictureOrientation property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTakePictureResponse_PictureOrientation_RawValue(TakePictureResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
