// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code AspectRatio}
 */
public  final class AspectRatio extends
    com.google.protobuf.GeneratedMessageLite<
        AspectRatio, AspectRatio.Builder> implements
    // @@protoc_insertion_point(message_implements:AspectRatio)
    AspectRatioOrBuilder {
  private AspectRatio() {
  }
  public static final int X_FIELD_NUMBER = 1;
  private int x_;
  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }
  /**
   * <code>int32 x = 1;</code>
   * @param value The x to set.
   */
  private void setX(int value) {
    
    x_ = value;
  }
  /**
   * <code>int32 x = 1;</code>
   */
  private void clearX() {
    
    x_ = 0;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private int y_;
  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }
  /**
   * <code>int32 y = 2;</code>
   * @param value The y to set.
   */
  private void setY(int value) {
    
    y_ = value;
  }
  /**
   * <code>int32 y = 2;</code>
   */
  private void clearY() {
    
    y_ = 0;
  }

  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.AspectRatio parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.AspectRatio prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code AspectRatio}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.AspectRatio, Builder> implements
      // @@protoc_insertion_point(builder_implements:AspectRatio)
      eu.long1.nativecamera.proto.AspectRatioOrBuilder {
    // Construct using eu.long1.nativecamera.proto.AspectRatio.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return instance.getX();
    }
    /**
     * <code>int32 x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {
      copyOnWrite();
      instance.setX(value);
      return this;
    }
    /**
     * <code>int32 x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      copyOnWrite();
      instance.clearX();
      return this;
    }

    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return instance.getY();
    }
    /**
     * <code>int32 y = 2;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {
      copyOnWrite();
      instance.setY(value);
      return this;
    }
    /**
     * <code>int32 y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      copyOnWrite();
      instance.clearY();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AspectRatio)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.AspectRatio();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "x_",
            "y_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.AspectRatio> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.AspectRatio.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.AspectRatio>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:AspectRatio)
  private static final eu.long1.nativecamera.proto.AspectRatio DEFAULT_INSTANCE;
  static {
    AspectRatio defaultInstance = new AspectRatio();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AspectRatio.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.AspectRatio getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AspectRatio> PARSER;

  public static com.google.protobuf.Parser<AspectRatio> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

