// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

public interface CameraStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraState)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>float zoom = 1;</code>
   * @return The zoom.
   */
  float getZoom();

  /**
   * <pre>
   * Only used on iOS
   * </pre>
   *
   * <code>float max_zoom = 2;</code>
   * @return The maxZoom.
   */
  float getMaxZoom();

  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   * @return Whether the ratio field is set.
   */
  boolean hasRatio();
  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   * @return The ratio.
   */
  eu.long1.nativecamera.proto.CameraAspectRatio getRatio();

  /**
   * <code>float focus_depth = 4;</code>
   * @return The focusDepth.
   */
  float getFocusDepth();

  /**
   * <code>string camera_id = 5;</code>
   * @return The cameraId.
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 5;</code>
   * @return The bytes for cameraId.
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <code>bool auto_focus = 6;</code>
   * @return The autoFocus.
   */
  boolean getAutoFocus();

  /**
   * <code>.CameraState.Flash flash = 7;</code>
   * @return The enum numeric value on the wire for flash.
   */
  int getFlashValue();
  /**
   * <code>.CameraState.Flash flash = 7;</code>
   * @return The flash.
   */
  eu.long1.nativecamera.proto.CameraState.Flash getFlash();

  /**
   * <code>float exposure = 8;</code>
   * @return The exposure.
   */
  float getExposure();

  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   * @return The enum numeric value on the wire for whiteBalance.
   */
  int getWhiteBalanceValue();
  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   * @return The whiteBalance.
   */
  eu.long1.nativecamera.proto.CameraState.WhiteBalance getWhiteBalance();

  /**
   * <code>bool play_sound_on_capture = 10;</code>
   * @return The playSoundOnCapture.
   */
  boolean getPlaySoundOnCapture();

  /**
   * <pre>
   * Only used on Android &gt; 21
   * </pre>
   *
   * <code>bool use_camera_2 = 11;</code>
   * @return The useCamera2.
   */
  boolean getUseCamera2();

  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @return The enum numeric value on the wire for orientation.
   */
  int getOrientationValue();
  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @return The orientation.
   */
  eu.long1.nativecamera.proto.CameraState.Orientation getOrientation();

  /**
   * <code>.Size preview_size = 13;</code>
   * @return Whether the previewSize field is set.
   */
  boolean hasPreviewSize();
  /**
   * <code>.Size preview_size = 13;</code>
   * @return The previewSize.
   */
  eu.long1.nativecamera.proto.Size getPreviewSize();

  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  java.util.List<eu.long1.nativecamera.proto.CameraAspectRatio> 
      getSupportedRatioList();
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  eu.long1.nativecamera.proto.CameraAspectRatio getSupportedRatio(int index);
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  int getSupportedRatioCount();

  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  java.util.List<eu.long1.nativecamera.proto.Range> 
      getSupportedPreviewFpsList();
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  eu.long1.nativecamera.proto.Range getSupportedPreviewFps(int index);
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  int getSupportedPreviewFpsCount();
}
