// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code CameraInfo}
 */
public  final class CameraInfo extends
    com.google.protobuf.GeneratedMessageLite<
        CameraInfo, CameraInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:CameraInfo)
    CameraInfoOrBuilder {
  private CameraInfo() {
    id_ = "";
  }
  /**
   * Protobuf enum {@code CameraInfo.LensFacing}
   */
  public enum LensFacing
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>FRONT = 0;</code>
     */
    FRONT(0),
    /**
     * <code>BACK = 1;</code>
     */
    BACK(1),
    /**
     * <code>EXTERNAL = 2;</code>
     */
    EXTERNAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FRONT = 0;</code>
     */
    public static final int FRONT_VALUE = 0;
    /**
     * <code>BACK = 1;</code>
     */
    public static final int BACK_VALUE = 1;
    /**
     * <code>EXTERNAL = 2;</code>
     */
    public static final int EXTERNAL_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LensFacing valueOf(int value) {
      return forNumber(value);
    }

    public static LensFacing forNumber(int value) {
      switch (value) {
        case 0: return FRONT;
        case 1: return BACK;
        case 2: return EXTERNAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LensFacing>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LensFacing> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LensFacing>() {
            @java.lang.Override
            public LensFacing findValueByNumber(int number) {
              return LensFacing.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return LensFacingVerifier.INSTANCE;
    }

    private static final class LensFacingVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new LensFacingVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return LensFacing.forNumber(number) != null;
            }
          };

    private final int value;

    private LensFacing(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraInfo.LensFacing)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    value.getClass();
  
    id_ = value;
  }
  /**
   * <code>string id = 1;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int FACING_FIELD_NUMBER = 2;
  private int facing_;
  /**
   * <code>.CameraInfo.LensFacing facing = 2;</code>
   * @return The enum numeric value on the wire for facing.
   */
  @java.lang.Override
  public int getFacingValue() {
    return facing_;
  }
  /**
   * <code>.CameraInfo.LensFacing facing = 2;</code>
   * @return The facing.
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraInfo.LensFacing getFacing() {
    eu.long1.nativecamera.proto.CameraInfo.LensFacing result = eu.long1.nativecamera.proto.CameraInfo.LensFacing.forNumber(facing_);
    return result == null ? eu.long1.nativecamera.proto.CameraInfo.LensFacing.UNRECOGNIZED : result;
  }
  /**
   * <code>.CameraInfo.LensFacing facing = 2;</code>
   * @param value The enum numeric value on the wire for facing to set.
   */
  private void setFacingValue(int value) {
      facing_ = value;
  }
  /**
   * <code>.CameraInfo.LensFacing facing = 2;</code>
   * @param value The facing to set.
   */
  private void setFacing(eu.long1.nativecamera.proto.CameraInfo.LensFacing value) {
    facing_ = value.getNumber();
    
  }
  /**
   * <code>.CameraInfo.LensFacing facing = 2;</code>
   */
  private void clearFacing() {
    
    facing_ = 0;
  }

  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.CameraInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.CameraInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CameraInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.CameraInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:CameraInfo)
      eu.long1.nativecamera.proto.CameraInfoOrBuilder {
    // Construct using eu.long1.nativecamera.proto.CameraInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>.CameraInfo.LensFacing facing = 2;</code>
     * @return The enum numeric value on the wire for facing.
     */
    @java.lang.Override
    public int getFacingValue() {
      return instance.getFacingValue();
    }
    /**
     * <code>.CameraInfo.LensFacing facing = 2;</code>
     * @param value The facing to set.
     * @return This builder for chaining.
     */
    public Builder setFacingValue(int value) {
      copyOnWrite();
      instance.setFacingValue(value);
      return this;
    }
    /**
     * <code>.CameraInfo.LensFacing facing = 2;</code>
     * @return The facing.
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraInfo.LensFacing getFacing() {
      return instance.getFacing();
    }
    /**
     * <code>.CameraInfo.LensFacing facing = 2;</code>
     * @param value The enum numeric value on the wire for facing to set.
     * @return This builder for chaining.
     */
    public Builder setFacing(eu.long1.nativecamera.proto.CameraInfo.LensFacing value) {
      copyOnWrite();
      instance.setFacing(value);
      return this;
    }
    /**
     * <code>.CameraInfo.LensFacing facing = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFacing() {
      copyOnWrite();
      instance.clearFacing();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CameraInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.CameraInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "facing_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\f" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.CameraInfo> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.CameraInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.CameraInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CameraInfo)
  private static final eu.long1.nativecamera.proto.CameraInfo DEFAULT_INSTANCE;
  static {
    CameraInfo defaultInstance = new CameraInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CameraInfo.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.CameraInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CameraInfo> PARSER;

  public static com.google.protobuf.Parser<CameraInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

