// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

public interface CameraAspectRatioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAspectRatio)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();
}
