// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code CameraState}
 */
public  final class CameraState extends
    com.google.protobuf.GeneratedMessageLite<
        CameraState, CameraState.Builder> implements
    // @@protoc_insertion_point(message_implements:CameraState)
    CameraStateOrBuilder {
  private CameraState() {
    cameraId_ = "";
    supportedRatio_ = emptyProtobufList();
    supportedPreviewFps_ = emptyProtobufList();
  }
  /**
   * Protobuf enum {@code CameraState.Flash}
   */
  public enum Flash
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>FLASH_ON = 0;</code>
     */
    FLASH_ON(0),
    /**
     * <code>FLASH_AUTO = 1;</code>
     */
    FLASH_AUTO(1),
    /**
     * <code>FLASH_OFF = 2;</code>
     */
    FLASH_OFF(2),
    /**
     * <code>FLASH_TORCH = 3;</code>
     */
    FLASH_TORCH(3),
    /**
     * <pre>
     * Available only on Android
     * </pre>
     *
     * <code>FLASH_RED_EYE = 4;</code>
     */
    FLASH_RED_EYE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FLASH_ON = 0;</code>
     */
    public static final int FLASH_ON_VALUE = 0;
    /**
     * <code>FLASH_AUTO = 1;</code>
     */
    public static final int FLASH_AUTO_VALUE = 1;
    /**
     * <code>FLASH_OFF = 2;</code>
     */
    public static final int FLASH_OFF_VALUE = 2;
    /**
     * <code>FLASH_TORCH = 3;</code>
     */
    public static final int FLASH_TORCH_VALUE = 3;
    /**
     * <pre>
     * Available only on Android
     * </pre>
     *
     * <code>FLASH_RED_EYE = 4;</code>
     */
    public static final int FLASH_RED_EYE_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Flash valueOf(int value) {
      return forNumber(value);
    }

    public static Flash forNumber(int value) {
      switch (value) {
        case 0: return FLASH_ON;
        case 1: return FLASH_AUTO;
        case 2: return FLASH_OFF;
        case 3: return FLASH_TORCH;
        case 4: return FLASH_RED_EYE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Flash>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Flash> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Flash>() {
            @java.lang.Override
            public Flash findValueByNumber(int number) {
              return Flash.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return FlashVerifier.INSTANCE;
    }

    private static final class FlashVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new FlashVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Flash.forNumber(number) != null;
            }
          };

    private final int value;

    private Flash(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraState.Flash)
  }

  /**
   * Protobuf enum {@code CameraState.Orientation}
   */
  public enum Orientation
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ORIENTATION_AUTO = 0;</code>
     */
    ORIENTATION_AUTO(0),
    /**
     * <code>ORIENTATION_LEFT = 1;</code>
     */
    ORIENTATION_LEFT(1),
    /**
     * <code>ORIENTATION_RIGHT = 2;</code>
     */
    ORIENTATION_RIGHT(2),
    /**
     * <code>ORIENTATION_UP = 3;</code>
     */
    ORIENTATION_UP(3),
    /**
     * <code>ORIENTATION_DOWN = 4;</code>
     */
    ORIENTATION_DOWN(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ORIENTATION_AUTO = 0;</code>
     */
    public static final int ORIENTATION_AUTO_VALUE = 0;
    /**
     * <code>ORIENTATION_LEFT = 1;</code>
     */
    public static final int ORIENTATION_LEFT_VALUE = 1;
    /**
     * <code>ORIENTATION_RIGHT = 2;</code>
     */
    public static final int ORIENTATION_RIGHT_VALUE = 2;
    /**
     * <code>ORIENTATION_UP = 3;</code>
     */
    public static final int ORIENTATION_UP_VALUE = 3;
    /**
     * <code>ORIENTATION_DOWN = 4;</code>
     */
    public static final int ORIENTATION_DOWN_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Orientation valueOf(int value) {
      return forNumber(value);
    }

    public static Orientation forNumber(int value) {
      switch (value) {
        case 0: return ORIENTATION_AUTO;
        case 1: return ORIENTATION_LEFT;
        case 2: return ORIENTATION_RIGHT;
        case 3: return ORIENTATION_UP;
        case 4: return ORIENTATION_DOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Orientation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Orientation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Orientation>() {
            @java.lang.Override
            public Orientation findValueByNumber(int number) {
              return Orientation.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return OrientationVerifier.INSTANCE;
    }

    private static final class OrientationVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new OrientationVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Orientation.forNumber(number) != null;
            }
          };

    private final int value;

    private Orientation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraState.Orientation)
  }

  /**
   * <pre>
   * Only used on iOS
   * </pre>
   *
   * Protobuf enum {@code CameraState.VideoCodec}
   */
  public enum VideoCodec
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>VIDEO_CODEC_APPLE_PRO_RES422 = 0;</code>
     */
    VIDEO_CODEC_APPLE_PRO_RES422(0),
    /**
     * <code>VIDEO_CODEC_APPLE_PRO_RES4444 = 1;</code>
     */
    VIDEO_CODEC_APPLE_PRO_RES4444(1),
    /**
     * <code>VIDEO_CODEC_H264 = 2;</code>
     */
    VIDEO_CODEC_H264(2),
    /**
     * <code>VIDEO_CODEC_HVEC = 3;</code>
     */
    VIDEO_CODEC_HVEC(3),
    /**
     * <code>VIDEO_CODEC_JPEG = 4;</code>
     */
    VIDEO_CODEC_JPEG(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VIDEO_CODEC_APPLE_PRO_RES422 = 0;</code>
     */
    public static final int VIDEO_CODEC_APPLE_PRO_RES422_VALUE = 0;
    /**
     * <code>VIDEO_CODEC_APPLE_PRO_RES4444 = 1;</code>
     */
    public static final int VIDEO_CODEC_APPLE_PRO_RES4444_VALUE = 1;
    /**
     * <code>VIDEO_CODEC_H264 = 2;</code>
     */
    public static final int VIDEO_CODEC_H264_VALUE = 2;
    /**
     * <code>VIDEO_CODEC_HVEC = 3;</code>
     */
    public static final int VIDEO_CODEC_HVEC_VALUE = 3;
    /**
     * <code>VIDEO_CODEC_JPEG = 4;</code>
     */
    public static final int VIDEO_CODEC_JPEG_VALUE = 4;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VideoCodec valueOf(int value) {
      return forNumber(value);
    }

    public static VideoCodec forNumber(int value) {
      switch (value) {
        case 0: return VIDEO_CODEC_APPLE_PRO_RES422;
        case 1: return VIDEO_CODEC_APPLE_PRO_RES4444;
        case 2: return VIDEO_CODEC_H264;
        case 3: return VIDEO_CODEC_HVEC;
        case 4: return VIDEO_CODEC_JPEG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VideoCodec>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VideoCodec> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VideoCodec>() {
            @java.lang.Override
            public VideoCodec findValueByNumber(int number) {
              return VideoCodec.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return VideoCodecVerifier.INSTANCE;
    }

    private static final class VideoCodecVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new VideoCodecVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return VideoCodec.forNumber(number) != null;
            }
          };

    private final int value;

    private VideoCodec(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraState.VideoCodec)
  }

  /**
   * Protobuf enum {@code CameraState.VideoQuality}
   */
  public enum VideoQuality
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>VIDEO_QUALITY_2160P = 0;</code>
     */
    VIDEO_QUALITY_2160P(0),
    /**
     * <code>VIDEO_QUALITY_1080P = 1;</code>
     */
    VIDEO_QUALITY_1080P(1),
    /**
     * <code>VIDEO_QUALITY_720P = 2;</code>
     */
    VIDEO_QUALITY_720P(2),
    /**
     * <code>VIDEO_QUALITY_480P = 3;</code>
     */
    VIDEO_QUALITY_480P(3),
    /**
     * <code>VIDEO_QUALITY_4_3 = 4;</code>
     */
    VIDEO_QUALITY_4_3(4),
    /**
     * <pre>
     * Available only on iOS
     * </pre>
     *
     * <code>VIDEO_QUALITY_288P = 5;</code>
     */
    VIDEO_QUALITY_288P(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VIDEO_QUALITY_2160P = 0;</code>
     */
    public static final int VIDEO_QUALITY_2160P_VALUE = 0;
    /**
     * <code>VIDEO_QUALITY_1080P = 1;</code>
     */
    public static final int VIDEO_QUALITY_1080P_VALUE = 1;
    /**
     * <code>VIDEO_QUALITY_720P = 2;</code>
     */
    public static final int VIDEO_QUALITY_720P_VALUE = 2;
    /**
     * <code>VIDEO_QUALITY_480P = 3;</code>
     */
    public static final int VIDEO_QUALITY_480P_VALUE = 3;
    /**
     * <code>VIDEO_QUALITY_4_3 = 4;</code>
     */
    public static final int VIDEO_QUALITY_4_3_VALUE = 4;
    /**
     * <pre>
     * Available only on iOS
     * </pre>
     *
     * <code>VIDEO_QUALITY_288P = 5;</code>
     */
    public static final int VIDEO_QUALITY_288P_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VideoQuality valueOf(int value) {
      return forNumber(value);
    }

    public static VideoQuality forNumber(int value) {
      switch (value) {
        case 0: return VIDEO_QUALITY_2160P;
        case 1: return VIDEO_QUALITY_1080P;
        case 2: return VIDEO_QUALITY_720P;
        case 3: return VIDEO_QUALITY_480P;
        case 4: return VIDEO_QUALITY_4_3;
        case 5: return VIDEO_QUALITY_288P;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VideoQuality>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VideoQuality> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VideoQuality>() {
            @java.lang.Override
            public VideoQuality findValueByNumber(int number) {
              return VideoQuality.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return VideoQualityVerifier.INSTANCE;
    }

    private static final class VideoQualityVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new VideoQualityVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return VideoQuality.forNumber(number) != null;
            }
          };

    private final int value;

    private VideoQuality(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraState.VideoQuality)
  }

  /**
   * <pre>
   * Only used on iOS
   * </pre>
   *
   * Protobuf enum {@code CameraState.VideoStabilization}
   */
  public enum VideoStabilization
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>VIDEO_STABILIZATION_AUTO = 0;</code>
     */
    VIDEO_STABILIZATION_AUTO(0),
    /**
     * <code>VIDEO_STABILIZATION_STANDARD = 1;</code>
     */
    VIDEO_STABILIZATION_STANDARD(1),
    /**
     * <code>VIDEO_STABILIZATION_OFF = 2;</code>
     */
    VIDEO_STABILIZATION_OFF(2),
    /**
     * <code>VIDEO_STABILIZATION_CINEMATIC = 3;</code>
     */
    VIDEO_STABILIZATION_CINEMATIC(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VIDEO_STABILIZATION_AUTO = 0;</code>
     */
    public static final int VIDEO_STABILIZATION_AUTO_VALUE = 0;
    /**
     * <code>VIDEO_STABILIZATION_STANDARD = 1;</code>
     */
    public static final int VIDEO_STABILIZATION_STANDARD_VALUE = 1;
    /**
     * <code>VIDEO_STABILIZATION_OFF = 2;</code>
     */
    public static final int VIDEO_STABILIZATION_OFF_VALUE = 2;
    /**
     * <code>VIDEO_STABILIZATION_CINEMATIC = 3;</code>
     */
    public static final int VIDEO_STABILIZATION_CINEMATIC_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VideoStabilization valueOf(int value) {
      return forNumber(value);
    }

    public static VideoStabilization forNumber(int value) {
      switch (value) {
        case 0: return VIDEO_STABILIZATION_AUTO;
        case 1: return VIDEO_STABILIZATION_STANDARD;
        case 2: return VIDEO_STABILIZATION_OFF;
        case 3: return VIDEO_STABILIZATION_CINEMATIC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VideoStabilization>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VideoStabilization> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VideoStabilization>() {
            @java.lang.Override
            public VideoStabilization findValueByNumber(int number) {
              return VideoStabilization.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return VideoStabilizationVerifier.INSTANCE;
    }

    private static final class VideoStabilizationVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new VideoStabilizationVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return VideoStabilization.forNumber(number) != null;
            }
          };

    private final int value;

    private VideoStabilization(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraState.VideoStabilization)
  }

  /**
   * Protobuf enum {@code CameraState.WhiteBalance}
   */
  public enum WhiteBalance
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>WHITE_BALANCE_AUTO = 0;</code>
     */
    WHITE_BALANCE_AUTO(0),
    /**
     * <code>WHITE_BALANCE_CLOUDY = 1;</code>
     */
    WHITE_BALANCE_CLOUDY(1),
    /**
     * <code>WHITE_BALANCE_FLUORESCENT = 2;</code>
     */
    WHITE_BALANCE_FLUORESCENT(2),
    /**
     * <code>WHITE_BALANCE_INCANDESCENT = 3;</code>
     */
    WHITE_BALANCE_INCANDESCENT(3),
    /**
     * <code>WHITE_BALANCE_SHADOW = 4;</code>
     */
    WHITE_BALANCE_SHADOW(4),
    /**
     * <code>WHITE_BALANCE_SUNNY = 5;</code>
     */
    WHITE_BALANCE_SUNNY(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WHITE_BALANCE_AUTO = 0;</code>
     */
    public static final int WHITE_BALANCE_AUTO_VALUE = 0;
    /**
     * <code>WHITE_BALANCE_CLOUDY = 1;</code>
     */
    public static final int WHITE_BALANCE_CLOUDY_VALUE = 1;
    /**
     * <code>WHITE_BALANCE_FLUORESCENT = 2;</code>
     */
    public static final int WHITE_BALANCE_FLUORESCENT_VALUE = 2;
    /**
     * <code>WHITE_BALANCE_INCANDESCENT = 3;</code>
     */
    public static final int WHITE_BALANCE_INCANDESCENT_VALUE = 3;
    /**
     * <code>WHITE_BALANCE_SHADOW = 4;</code>
     */
    public static final int WHITE_BALANCE_SHADOW_VALUE = 4;
    /**
     * <code>WHITE_BALANCE_SUNNY = 5;</code>
     */
    public static final int WHITE_BALANCE_SUNNY_VALUE = 5;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WhiteBalance valueOf(int value) {
      return forNumber(value);
    }

    public static WhiteBalance forNumber(int value) {
      switch (value) {
        case 0: return WHITE_BALANCE_AUTO;
        case 1: return WHITE_BALANCE_CLOUDY;
        case 2: return WHITE_BALANCE_FLUORESCENT;
        case 3: return WHITE_BALANCE_INCANDESCENT;
        case 4: return WHITE_BALANCE_SHADOW;
        case 5: return WHITE_BALANCE_SUNNY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WhiteBalance>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WhiteBalance> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WhiteBalance>() {
            @java.lang.Override
            public WhiteBalance findValueByNumber(int number) {
              return WhiteBalance.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return WhiteBalanceVerifier.INSTANCE;
    }

    private static final class WhiteBalanceVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WhiteBalanceVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return WhiteBalance.forNumber(number) != null;
            }
          };

    private final int value;

    private WhiteBalance(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraState.WhiteBalance)
  }

  public static final int ZOOM_FIELD_NUMBER = 1;
  private float zoom_;
  /**
   * <code>float zoom = 1;</code>
   * @return The zoom.
   */
  @java.lang.Override
  public float getZoom() {
    return zoom_;
  }
  /**
   * <code>float zoom = 1;</code>
   * @param value The zoom to set.
   */
  private void setZoom(float value) {
    
    zoom_ = value;
  }
  /**
   * <code>float zoom = 1;</code>
   */
  private void clearZoom() {
    
    zoom_ = 0F;
  }

  public static final int MAX_ZOOM_FIELD_NUMBER = 2;
  private float maxZoom_;
  /**
   * <pre>
   * Only used on iOS
   * </pre>
   *
   * <code>float max_zoom = 2;</code>
   * @return The maxZoom.
   */
  @java.lang.Override
  public float getMaxZoom() {
    return maxZoom_;
  }
  /**
   * <pre>
   * Only used on iOS
   * </pre>
   *
   * <code>float max_zoom = 2;</code>
   * @param value The maxZoom to set.
   */
  private void setMaxZoom(float value) {
    
    maxZoom_ = value;
  }
  /**
   * <pre>
   * Only used on iOS
   * </pre>
   *
   * <code>float max_zoom = 2;</code>
   */
  private void clearMaxZoom() {
    
    maxZoom_ = 0F;
  }

  public static final int RATIO_FIELD_NUMBER = 3;
  private eu.long1.nativecamera.proto.CameraAspectRatio ratio_;
  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   */
  @java.lang.Override
  public boolean hasRatio() {
    return ratio_ != null;
  }
  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraAspectRatio getRatio() {
    return ratio_ == null ? eu.long1.nativecamera.proto.CameraAspectRatio.getDefaultInstance() : ratio_;
  }
  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   */
  private void setRatio(eu.long1.nativecamera.proto.CameraAspectRatio value) {
    value.getClass();
  ratio_ = value;
    
    }
  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeRatio(eu.long1.nativecamera.proto.CameraAspectRatio value) {
    value.getClass();
  if (ratio_ != null &&
        ratio_ != eu.long1.nativecamera.proto.CameraAspectRatio.getDefaultInstance()) {
      ratio_ =
        eu.long1.nativecamera.proto.CameraAspectRatio.newBuilder(ratio_).mergeFrom(value).buildPartial();
    } else {
      ratio_ = value;
    }
    
  }
  /**
   * <code>.CameraAspectRatio ratio = 3;</code>
   */
  private void clearRatio() {  ratio_ = null;
    
  }

  public static final int FOCUS_DEPTH_FIELD_NUMBER = 4;
  private float focusDepth_;
  /**
   * <code>float focus_depth = 4;</code>
   * @return The focusDepth.
   */
  @java.lang.Override
  public float getFocusDepth() {
    return focusDepth_;
  }
  /**
   * <code>float focus_depth = 4;</code>
   * @param value The focusDepth to set.
   */
  private void setFocusDepth(float value) {
    
    focusDepth_ = value;
  }
  /**
   * <code>float focus_depth = 4;</code>
   */
  private void clearFocusDepth() {
    
    focusDepth_ = 0F;
  }

  public static final int CAMERA_ID_FIELD_NUMBER = 5;
  private java.lang.String cameraId_;
  /**
   * <code>string camera_id = 5;</code>
   * @return The cameraId.
   */
  @java.lang.Override
  public java.lang.String getCameraId() {
    return cameraId_;
  }
  /**
   * <code>string camera_id = 5;</code>
   * @return The bytes for cameraId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCameraIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(cameraId_);
  }
  /**
   * <code>string camera_id = 5;</code>
   * @param value The cameraId to set.
   */
  private void setCameraId(
      java.lang.String value) {
    value.getClass();
  
    cameraId_ = value;
  }
  /**
   * <code>string camera_id = 5;</code>
   */
  private void clearCameraId() {
    
    cameraId_ = getDefaultInstance().getCameraId();
  }
  /**
   * <code>string camera_id = 5;</code>
   * @param value The bytes for cameraId to set.
   */
  private void setCameraIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    cameraId_ = value.toStringUtf8();
    
  }

  public static final int AUTO_FOCUS_FIELD_NUMBER = 6;
  private boolean autoFocus_;
  /**
   * <code>bool auto_focus = 6;</code>
   * @return The autoFocus.
   */
  @java.lang.Override
  public boolean getAutoFocus() {
    return autoFocus_;
  }
  /**
   * <code>bool auto_focus = 6;</code>
   * @param value The autoFocus to set.
   */
  private void setAutoFocus(boolean value) {
    
    autoFocus_ = value;
  }
  /**
   * <code>bool auto_focus = 6;</code>
   */
  private void clearAutoFocus() {
    
    autoFocus_ = false;
  }

  public static final int FLASH_FIELD_NUMBER = 7;
  private int flash_;
  /**
   * <code>.CameraState.Flash flash = 7;</code>
   * @return The enum numeric value on the wire for flash.
   */
  @java.lang.Override
  public int getFlashValue() {
    return flash_;
  }
  /**
   * <code>.CameraState.Flash flash = 7;</code>
   * @return The flash.
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState.Flash getFlash() {
    eu.long1.nativecamera.proto.CameraState.Flash result = eu.long1.nativecamera.proto.CameraState.Flash.forNumber(flash_);
    return result == null ? eu.long1.nativecamera.proto.CameraState.Flash.UNRECOGNIZED : result;
  }
  /**
   * <code>.CameraState.Flash flash = 7;</code>
   * @param value The enum numeric value on the wire for flash to set.
   */
  private void setFlashValue(int value) {
      flash_ = value;
  }
  /**
   * <code>.CameraState.Flash flash = 7;</code>
   * @param value The flash to set.
   */
  private void setFlash(eu.long1.nativecamera.proto.CameraState.Flash value) {
    flash_ = value.getNumber();
    
  }
  /**
   * <code>.CameraState.Flash flash = 7;</code>
   */
  private void clearFlash() {
    
    flash_ = 0;
  }

  public static final int EXPOSURE_FIELD_NUMBER = 8;
  private float exposure_;
  /**
   * <code>float exposure = 8;</code>
   * @return The exposure.
   */
  @java.lang.Override
  public float getExposure() {
    return exposure_;
  }
  /**
   * <code>float exposure = 8;</code>
   * @param value The exposure to set.
   */
  private void setExposure(float value) {
    
    exposure_ = value;
  }
  /**
   * <code>float exposure = 8;</code>
   */
  private void clearExposure() {
    
    exposure_ = 0F;
  }

  public static final int WHITE_BALANCE_FIELD_NUMBER = 9;
  private int whiteBalance_;
  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   * @return The enum numeric value on the wire for whiteBalance.
   */
  @java.lang.Override
  public int getWhiteBalanceValue() {
    return whiteBalance_;
  }
  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   * @return The whiteBalance.
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState.WhiteBalance getWhiteBalance() {
    eu.long1.nativecamera.proto.CameraState.WhiteBalance result = eu.long1.nativecamera.proto.CameraState.WhiteBalance.forNumber(whiteBalance_);
    return result == null ? eu.long1.nativecamera.proto.CameraState.WhiteBalance.UNRECOGNIZED : result;
  }
  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   * @param value The enum numeric value on the wire for whiteBalance to set.
   */
  private void setWhiteBalanceValue(int value) {
      whiteBalance_ = value;
  }
  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   * @param value The whiteBalance to set.
   */
  private void setWhiteBalance(eu.long1.nativecamera.proto.CameraState.WhiteBalance value) {
    whiteBalance_ = value.getNumber();
    
  }
  /**
   * <code>.CameraState.WhiteBalance white_balance = 9;</code>
   */
  private void clearWhiteBalance() {
    
    whiteBalance_ = 0;
  }

  public static final int PLAY_SOUND_ON_CAPTURE_FIELD_NUMBER = 10;
  private boolean playSoundOnCapture_;
  /**
   * <code>bool play_sound_on_capture = 10;</code>
   * @return The playSoundOnCapture.
   */
  @java.lang.Override
  public boolean getPlaySoundOnCapture() {
    return playSoundOnCapture_;
  }
  /**
   * <code>bool play_sound_on_capture = 10;</code>
   * @param value The playSoundOnCapture to set.
   */
  private void setPlaySoundOnCapture(boolean value) {
    
    playSoundOnCapture_ = value;
  }
  /**
   * <code>bool play_sound_on_capture = 10;</code>
   */
  private void clearPlaySoundOnCapture() {
    
    playSoundOnCapture_ = false;
  }

  public static final int USE_CAMERA_2_FIELD_NUMBER = 11;
  private boolean useCamera2_;
  /**
   * <pre>
   * Only used on Android &gt; 21
   * </pre>
   *
   * <code>bool use_camera_2 = 11;</code>
   * @return The useCamera2.
   */
  @java.lang.Override
  public boolean getUseCamera2() {
    return useCamera2_;
  }
  /**
   * <pre>
   * Only used on Android &gt; 21
   * </pre>
   *
   * <code>bool use_camera_2 = 11;</code>
   * @param value The useCamera2 to set.
   */
  private void setUseCamera2(boolean value) {
    
    useCamera2_ = value;
  }
  /**
   * <pre>
   * Only used on Android &gt; 21
   * </pre>
   *
   * <code>bool use_camera_2 = 11;</code>
   */
  private void clearUseCamera2() {
    
    useCamera2_ = false;
  }

  public static final int ORIENTATION_FIELD_NUMBER = 12;
  private int orientation_;
  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @return The enum numeric value on the wire for orientation.
   */
  @java.lang.Override
  public int getOrientationValue() {
    return orientation_;
  }
  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @return The orientation.
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState.Orientation getOrientation() {
    eu.long1.nativecamera.proto.CameraState.Orientation result = eu.long1.nativecamera.proto.CameraState.Orientation.forNumber(orientation_);
    return result == null ? eu.long1.nativecamera.proto.CameraState.Orientation.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @param value The enum numeric value on the wire for orientation to set.
   */
  private void setOrientationValue(int value) {
      orientation_ = value;
  }
  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @param value The orientation to set.
   */
  private void setOrientation(eu.long1.nativecamera.proto.CameraState.Orientation value) {
    orientation_ = value.getNumber();
    
  }
  /**
   * <pre>
   * read only
   * </pre>
   *
   * <code>.CameraState.Orientation orientation = 12;</code>
   */
  private void clearOrientation() {
    
    orientation_ = 0;
  }

  public static final int PREVIEW_SIZE_FIELD_NUMBER = 13;
  private eu.long1.nativecamera.proto.Size previewSize_;
  /**
   * <code>.Size preview_size = 13;</code>
   */
  @java.lang.Override
  public boolean hasPreviewSize() {
    return previewSize_ != null;
  }
  /**
   * <code>.Size preview_size = 13;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.Size getPreviewSize() {
    return previewSize_ == null ? eu.long1.nativecamera.proto.Size.getDefaultInstance() : previewSize_;
  }
  /**
   * <code>.Size preview_size = 13;</code>
   */
  private void setPreviewSize(eu.long1.nativecamera.proto.Size value) {
    value.getClass();
  previewSize_ = value;
    
    }
  /**
   * <code>.Size preview_size = 13;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePreviewSize(eu.long1.nativecamera.proto.Size value) {
    value.getClass();
  if (previewSize_ != null &&
        previewSize_ != eu.long1.nativecamera.proto.Size.getDefaultInstance()) {
      previewSize_ =
        eu.long1.nativecamera.proto.Size.newBuilder(previewSize_).mergeFrom(value).buildPartial();
    } else {
      previewSize_ = value;
    }
    
  }
  /**
   * <code>.Size preview_size = 13;</code>
   */
  private void clearPreviewSize() {  previewSize_ = null;
    
  }

  public static final int SUPPORTED_RATIO_FIELD_NUMBER = 14;
  private com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.CameraAspectRatio> supportedRatio_;
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  @java.lang.Override
  public java.util.List<eu.long1.nativecamera.proto.CameraAspectRatio> getSupportedRatioList() {
    return supportedRatio_;
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  public java.util.List<? extends eu.long1.nativecamera.proto.CameraAspectRatioOrBuilder> 
      getSupportedRatioOrBuilderList() {
    return supportedRatio_;
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  @java.lang.Override
  public int getSupportedRatioCount() {
    return supportedRatio_.size();
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraAspectRatio getSupportedRatio(int index) {
    return supportedRatio_.get(index);
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  public eu.long1.nativecamera.proto.CameraAspectRatioOrBuilder getSupportedRatioOrBuilder(
      int index) {
    return supportedRatio_.get(index);
  }
  private void ensureSupportedRatioIsMutable() {
    com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.CameraAspectRatio> tmp = supportedRatio_;
    if (!tmp.isModifiable()) {
      supportedRatio_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  private void setSupportedRatio(
      int index, eu.long1.nativecamera.proto.CameraAspectRatio value) {
    value.getClass();
  ensureSupportedRatioIsMutable();
    supportedRatio_.set(index, value);
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  private void addSupportedRatio(eu.long1.nativecamera.proto.CameraAspectRatio value) {
    value.getClass();
  ensureSupportedRatioIsMutable();
    supportedRatio_.add(value);
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  private void addSupportedRatio(
      int index, eu.long1.nativecamera.proto.CameraAspectRatio value) {
    value.getClass();
  ensureSupportedRatioIsMutable();
    supportedRatio_.add(index, value);
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  private void addAllSupportedRatio(
      java.lang.Iterable<? extends eu.long1.nativecamera.proto.CameraAspectRatio> values) {
    ensureSupportedRatioIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, supportedRatio_);
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  private void clearSupportedRatio() {
    supportedRatio_ = emptyProtobufList();
  }
  /**
   * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
   */
  private void removeSupportedRatio(int index) {
    ensureSupportedRatioIsMutable();
    supportedRatio_.remove(index);
  }

  public static final int SUPPORTED_PREVIEW_FPS_FIELD_NUMBER = 15;
  private com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.Range> supportedPreviewFps_;
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  @java.lang.Override
  public java.util.List<eu.long1.nativecamera.proto.Range> getSupportedPreviewFpsList() {
    return supportedPreviewFps_;
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  public java.util.List<? extends eu.long1.nativecamera.proto.RangeOrBuilder> 
      getSupportedPreviewFpsOrBuilderList() {
    return supportedPreviewFps_;
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  @java.lang.Override
  public int getSupportedPreviewFpsCount() {
    return supportedPreviewFps_.size();
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.Range getSupportedPreviewFps(int index) {
    return supportedPreviewFps_.get(index);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  public eu.long1.nativecamera.proto.RangeOrBuilder getSupportedPreviewFpsOrBuilder(
      int index) {
    return supportedPreviewFps_.get(index);
  }
  private void ensureSupportedPreviewFpsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.Range> tmp = supportedPreviewFps_;
    if (!tmp.isModifiable()) {
      supportedPreviewFps_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  private void setSupportedPreviewFps(
      int index, eu.long1.nativecamera.proto.Range value) {
    value.getClass();
  ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.set(index, value);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  private void addSupportedPreviewFps(eu.long1.nativecamera.proto.Range value) {
    value.getClass();
  ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.add(value);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  private void addSupportedPreviewFps(
      int index, eu.long1.nativecamera.proto.Range value) {
    value.getClass();
  ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.add(index, value);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  private void addAllSupportedPreviewFps(
      java.lang.Iterable<? extends eu.long1.nativecamera.proto.Range> values) {
    ensureSupportedPreviewFpsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, supportedPreviewFps_);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  private void clearSupportedPreviewFps() {
    supportedPreviewFps_ = emptyProtobufList();
  }
  /**
   * <code>repeated .Range supported_preview_fps = 15;</code>
   */
  private void removeSupportedPreviewFps(int index) {
    ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.remove(index);
  }

  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.CameraState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.CameraState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.CameraState prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CameraState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.CameraState, Builder> implements
      // @@protoc_insertion_point(builder_implements:CameraState)
      eu.long1.nativecamera.proto.CameraStateOrBuilder {
    // Construct using eu.long1.nativecamera.proto.CameraState.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>float zoom = 1;</code>
     * @return The zoom.
     */
    @java.lang.Override
    public float getZoom() {
      return instance.getZoom();
    }
    /**
     * <code>float zoom = 1;</code>
     * @param value The zoom to set.
     * @return This builder for chaining.
     */
    public Builder setZoom(float value) {
      copyOnWrite();
      instance.setZoom(value);
      return this;
    }
    /**
     * <code>float zoom = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearZoom() {
      copyOnWrite();
      instance.clearZoom();
      return this;
    }

    /**
     * <pre>
     * Only used on iOS
     * </pre>
     *
     * <code>float max_zoom = 2;</code>
     * @return The maxZoom.
     */
    @java.lang.Override
    public float getMaxZoom() {
      return instance.getMaxZoom();
    }
    /**
     * <pre>
     * Only used on iOS
     * </pre>
     *
     * <code>float max_zoom = 2;</code>
     * @param value The maxZoom to set.
     * @return This builder for chaining.
     */
    public Builder setMaxZoom(float value) {
      copyOnWrite();
      instance.setMaxZoom(value);
      return this;
    }
    /**
     * <pre>
     * Only used on iOS
     * </pre>
     *
     * <code>float max_zoom = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxZoom() {
      copyOnWrite();
      instance.clearMaxZoom();
      return this;
    }

    /**
     * <code>.CameraAspectRatio ratio = 3;</code>
     */
    @java.lang.Override
    public boolean hasRatio() {
      return instance.hasRatio();
    }
    /**
     * <code>.CameraAspectRatio ratio = 3;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraAspectRatio getRatio() {
      return instance.getRatio();
    }
    /**
     * <code>.CameraAspectRatio ratio = 3;</code>
     */
    public Builder setRatio(eu.long1.nativecamera.proto.CameraAspectRatio value) {
      copyOnWrite();
      instance.setRatio(value);
      return this;
      }
    /**
     * <code>.CameraAspectRatio ratio = 3;</code>
     */
    public Builder setRatio(
        eu.long1.nativecamera.proto.CameraAspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.setRatio(builderForValue.build());
      return this;
    }
    /**
     * <code>.CameraAspectRatio ratio = 3;</code>
     */
    public Builder mergeRatio(eu.long1.nativecamera.proto.CameraAspectRatio value) {
      copyOnWrite();
      instance.mergeRatio(value);
      return this;
    }
    /**
     * <code>.CameraAspectRatio ratio = 3;</code>
     */
    public Builder clearRatio() {  copyOnWrite();
      instance.clearRatio();
      return this;
    }

    /**
     * <code>float focus_depth = 4;</code>
     * @return The focusDepth.
     */
    @java.lang.Override
    public float getFocusDepth() {
      return instance.getFocusDepth();
    }
    /**
     * <code>float focus_depth = 4;</code>
     * @param value The focusDepth to set.
     * @return This builder for chaining.
     */
    public Builder setFocusDepth(float value) {
      copyOnWrite();
      instance.setFocusDepth(value);
      return this;
    }
    /**
     * <code>float focus_depth = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFocusDepth() {
      copyOnWrite();
      instance.clearFocusDepth();
      return this;
    }

    /**
     * <code>string camera_id = 5;</code>
     * @return The cameraId.
     */
    @java.lang.Override
    public java.lang.String getCameraId() {
      return instance.getCameraId();
    }
    /**
     * <code>string camera_id = 5;</code>
     * @return The bytes for cameraId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCameraIdBytes() {
      return instance.getCameraIdBytes();
    }
    /**
     * <code>string camera_id = 5;</code>
     * @param value The cameraId to set.
     * @return This builder for chaining.
     */
    public Builder setCameraId(
        java.lang.String value) {
      copyOnWrite();
      instance.setCameraId(value);
      return this;
    }
    /**
     * <code>string camera_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCameraId() {
      copyOnWrite();
      instance.clearCameraId();
      return this;
    }
    /**
     * <code>string camera_id = 5;</code>
     * @param value The bytes for cameraId to set.
     * @return This builder for chaining.
     */
    public Builder setCameraIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCameraIdBytes(value);
      return this;
    }

    /**
     * <code>bool auto_focus = 6;</code>
     * @return The autoFocus.
     */
    @java.lang.Override
    public boolean getAutoFocus() {
      return instance.getAutoFocus();
    }
    /**
     * <code>bool auto_focus = 6;</code>
     * @param value The autoFocus to set.
     * @return This builder for chaining.
     */
    public Builder setAutoFocus(boolean value) {
      copyOnWrite();
      instance.setAutoFocus(value);
      return this;
    }
    /**
     * <code>bool auto_focus = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoFocus() {
      copyOnWrite();
      instance.clearAutoFocus();
      return this;
    }

    /**
     * <code>.CameraState.Flash flash = 7;</code>
     * @return The enum numeric value on the wire for flash.
     */
    @java.lang.Override
    public int getFlashValue() {
      return instance.getFlashValue();
    }
    /**
     * <code>.CameraState.Flash flash = 7;</code>
     * @param value The flash to set.
     * @return This builder for chaining.
     */
    public Builder setFlashValue(int value) {
      copyOnWrite();
      instance.setFlashValue(value);
      return this;
    }
    /**
     * <code>.CameraState.Flash flash = 7;</code>
     * @return The flash.
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState.Flash getFlash() {
      return instance.getFlash();
    }
    /**
     * <code>.CameraState.Flash flash = 7;</code>
     * @param value The enum numeric value on the wire for flash to set.
     * @return This builder for chaining.
     */
    public Builder setFlash(eu.long1.nativecamera.proto.CameraState.Flash value) {
      copyOnWrite();
      instance.setFlash(value);
      return this;
    }
    /**
     * <code>.CameraState.Flash flash = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlash() {
      copyOnWrite();
      instance.clearFlash();
      return this;
    }

    /**
     * <code>float exposure = 8;</code>
     * @return The exposure.
     */
    @java.lang.Override
    public float getExposure() {
      return instance.getExposure();
    }
    /**
     * <code>float exposure = 8;</code>
     * @param value The exposure to set.
     * @return This builder for chaining.
     */
    public Builder setExposure(float value) {
      copyOnWrite();
      instance.setExposure(value);
      return this;
    }
    /**
     * <code>float exposure = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearExposure() {
      copyOnWrite();
      instance.clearExposure();
      return this;
    }

    /**
     * <code>.CameraState.WhiteBalance white_balance = 9;</code>
     * @return The enum numeric value on the wire for whiteBalance.
     */
    @java.lang.Override
    public int getWhiteBalanceValue() {
      return instance.getWhiteBalanceValue();
    }
    /**
     * <code>.CameraState.WhiteBalance white_balance = 9;</code>
     * @param value The whiteBalance to set.
     * @return This builder for chaining.
     */
    public Builder setWhiteBalanceValue(int value) {
      copyOnWrite();
      instance.setWhiteBalanceValue(value);
      return this;
    }
    /**
     * <code>.CameraState.WhiteBalance white_balance = 9;</code>
     * @return The whiteBalance.
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState.WhiteBalance getWhiteBalance() {
      return instance.getWhiteBalance();
    }
    /**
     * <code>.CameraState.WhiteBalance white_balance = 9;</code>
     * @param value The enum numeric value on the wire for whiteBalance to set.
     * @return This builder for chaining.
     */
    public Builder setWhiteBalance(eu.long1.nativecamera.proto.CameraState.WhiteBalance value) {
      copyOnWrite();
      instance.setWhiteBalance(value);
      return this;
    }
    /**
     * <code>.CameraState.WhiteBalance white_balance = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearWhiteBalance() {
      copyOnWrite();
      instance.clearWhiteBalance();
      return this;
    }

    /**
     * <code>bool play_sound_on_capture = 10;</code>
     * @return The playSoundOnCapture.
     */
    @java.lang.Override
    public boolean getPlaySoundOnCapture() {
      return instance.getPlaySoundOnCapture();
    }
    /**
     * <code>bool play_sound_on_capture = 10;</code>
     * @param value The playSoundOnCapture to set.
     * @return This builder for chaining.
     */
    public Builder setPlaySoundOnCapture(boolean value) {
      copyOnWrite();
      instance.setPlaySoundOnCapture(value);
      return this;
    }
    /**
     * <code>bool play_sound_on_capture = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlaySoundOnCapture() {
      copyOnWrite();
      instance.clearPlaySoundOnCapture();
      return this;
    }

    /**
     * <pre>
     * Only used on Android &gt; 21
     * </pre>
     *
     * <code>bool use_camera_2 = 11;</code>
     * @return The useCamera2.
     */
    @java.lang.Override
    public boolean getUseCamera2() {
      return instance.getUseCamera2();
    }
    /**
     * <pre>
     * Only used on Android &gt; 21
     * </pre>
     *
     * <code>bool use_camera_2 = 11;</code>
     * @param value The useCamera2 to set.
     * @return This builder for chaining.
     */
    public Builder setUseCamera2(boolean value) {
      copyOnWrite();
      instance.setUseCamera2(value);
      return this;
    }
    /**
     * <pre>
     * Only used on Android &gt; 21
     * </pre>
     *
     * <code>bool use_camera_2 = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearUseCamera2() {
      copyOnWrite();
      instance.clearUseCamera2();
      return this;
    }

    /**
     * <pre>
     * read only
     * </pre>
     *
     * <code>.CameraState.Orientation orientation = 12;</code>
     * @return The enum numeric value on the wire for orientation.
     */
    @java.lang.Override
    public int getOrientationValue() {
      return instance.getOrientationValue();
    }
    /**
     * <pre>
     * read only
     * </pre>
     *
     * <code>.CameraState.Orientation orientation = 12;</code>
     * @param value The orientation to set.
     * @return This builder for chaining.
     */
    public Builder setOrientationValue(int value) {
      copyOnWrite();
      instance.setOrientationValue(value);
      return this;
    }
    /**
     * <pre>
     * read only
     * </pre>
     *
     * <code>.CameraState.Orientation orientation = 12;</code>
     * @return The orientation.
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState.Orientation getOrientation() {
      return instance.getOrientation();
    }
    /**
     * <pre>
     * read only
     * </pre>
     *
     * <code>.CameraState.Orientation orientation = 12;</code>
     * @param value The enum numeric value on the wire for orientation to set.
     * @return This builder for chaining.
     */
    public Builder setOrientation(eu.long1.nativecamera.proto.CameraState.Orientation value) {
      copyOnWrite();
      instance.setOrientation(value);
      return this;
    }
    /**
     * <pre>
     * read only
     * </pre>
     *
     * <code>.CameraState.Orientation orientation = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrientation() {
      copyOnWrite();
      instance.clearOrientation();
      return this;
    }

    /**
     * <code>.Size preview_size = 13;</code>
     */
    @java.lang.Override
    public boolean hasPreviewSize() {
      return instance.hasPreviewSize();
    }
    /**
     * <code>.Size preview_size = 13;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.Size getPreviewSize() {
      return instance.getPreviewSize();
    }
    /**
     * <code>.Size preview_size = 13;</code>
     */
    public Builder setPreviewSize(eu.long1.nativecamera.proto.Size value) {
      copyOnWrite();
      instance.setPreviewSize(value);
      return this;
      }
    /**
     * <code>.Size preview_size = 13;</code>
     */
    public Builder setPreviewSize(
        eu.long1.nativecamera.proto.Size.Builder builderForValue) {
      copyOnWrite();
      instance.setPreviewSize(builderForValue.build());
      return this;
    }
    /**
     * <code>.Size preview_size = 13;</code>
     */
    public Builder mergePreviewSize(eu.long1.nativecamera.proto.Size value) {
      copyOnWrite();
      instance.mergePreviewSize(value);
      return this;
    }
    /**
     * <code>.Size preview_size = 13;</code>
     */
    public Builder clearPreviewSize() {  copyOnWrite();
      instance.clearPreviewSize();
      return this;
    }

    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    @java.lang.Override
    public java.util.List<eu.long1.nativecamera.proto.CameraAspectRatio> getSupportedRatioList() {
      return java.util.Collections.unmodifiableList(
          instance.getSupportedRatioList());
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    @java.lang.Override
    public int getSupportedRatioCount() {
      return instance.getSupportedRatioCount();
    }/**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraAspectRatio getSupportedRatio(int index) {
      return instance.getSupportedRatio(index);
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder setSupportedRatio(
        int index, eu.long1.nativecamera.proto.CameraAspectRatio value) {
      copyOnWrite();
      instance.setSupportedRatio(index, value);
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder setSupportedRatio(
        int index, eu.long1.nativecamera.proto.CameraAspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.setSupportedRatio(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder addSupportedRatio(eu.long1.nativecamera.proto.CameraAspectRatio value) {
      copyOnWrite();
      instance.addSupportedRatio(value);
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder addSupportedRatio(
        int index, eu.long1.nativecamera.proto.CameraAspectRatio value) {
      copyOnWrite();
      instance.addSupportedRatio(index, value);
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder addSupportedRatio(
        eu.long1.nativecamera.proto.CameraAspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedRatio(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder addSupportedRatio(
        int index, eu.long1.nativecamera.proto.CameraAspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedRatio(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder addAllSupportedRatio(
        java.lang.Iterable<? extends eu.long1.nativecamera.proto.CameraAspectRatio> values) {
      copyOnWrite();
      instance.addAllSupportedRatio(values);
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder clearSupportedRatio() {
      copyOnWrite();
      instance.clearSupportedRatio();
      return this;
    }
    /**
     * <code>repeated .CameraAspectRatio supported_ratio = 14;</code>
     */
    public Builder removeSupportedRatio(int index) {
      copyOnWrite();
      instance.removeSupportedRatio(index);
      return this;
    }

    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    @java.lang.Override
    public java.util.List<eu.long1.nativecamera.proto.Range> getSupportedPreviewFpsList() {
      return java.util.Collections.unmodifiableList(
          instance.getSupportedPreviewFpsList());
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    @java.lang.Override
    public int getSupportedPreviewFpsCount() {
      return instance.getSupportedPreviewFpsCount();
    }/**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.Range getSupportedPreviewFps(int index) {
      return instance.getSupportedPreviewFps(index);
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder setSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range value) {
      copyOnWrite();
      instance.setSupportedPreviewFps(index, value);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder setSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range.Builder builderForValue) {
      copyOnWrite();
      instance.setSupportedPreviewFps(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder addSupportedPreviewFps(eu.long1.nativecamera.proto.Range value) {
      copyOnWrite();
      instance.addSupportedPreviewFps(value);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder addSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range value) {
      copyOnWrite();
      instance.addSupportedPreviewFps(index, value);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder addSupportedPreviewFps(
        eu.long1.nativecamera.proto.Range.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedPreviewFps(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder addSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedPreviewFps(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder addAllSupportedPreviewFps(
        java.lang.Iterable<? extends eu.long1.nativecamera.proto.Range> values) {
      copyOnWrite();
      instance.addAllSupportedPreviewFps(values);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder clearSupportedPreviewFps() {
      copyOnWrite();
      instance.clearSupportedPreviewFps();
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 15;</code>
     */
    public Builder removeSupportedPreviewFps(int index) {
      copyOnWrite();
      instance.removeSupportedPreviewFps(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CameraState)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.CameraState();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "zoom_",
            "maxZoom_",
            "ratio_",
            "focusDepth_",
            "cameraId_",
            "autoFocus_",
            "flash_",
            "exposure_",
            "whiteBalance_",
            "playSoundOnCapture_",
            "useCamera2_",
            "orientation_",
            "previewSize_",
            "supportedRatio_",
            eu.long1.nativecamera.proto.CameraAspectRatio.class,
            "supportedPreviewFps_",
            eu.long1.nativecamera.proto.Range.class,
          };
          java.lang.String info =
              "\u0000\u000f\u0000\u0000\u0001\u000f\u000f\u0000\u0002\u0000\u0001\u0001\u0002\u0001" +
              "\u0003\t\u0004\u0001\u0005\u0208\u0006\u0007\u0007\f\b\u0001\t\f\n\u0007\u000b\u0007" +
              "\f\f\r\t\u000e\u001b\u000f\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.CameraState> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.CameraState.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.CameraState>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CameraState)
  private static final eu.long1.nativecamera.proto.CameraState DEFAULT_INSTANCE;
  static {
    CameraState defaultInstance = new CameraState();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CameraState.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.CameraState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CameraState> PARSER;

  public static com.google.protobuf.Parser<CameraState> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

