// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

public interface InitializeCameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitializeCameraResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 textureId = 1;</code>
   * @return The textureId.
   */
  long getTextureId();

  /**
   * <code>.CameraState state = 2;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.CameraState state = 2;</code>
   * @return The state.
   */
  eu.long1.nativecamera.proto.CameraState getState();

  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   * @return The enum numeric value on the wire for orientation.
   */
  int getOrientationValue();
  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   * @return The orientation.
   */
  eu.long1.nativecamera.proto.CameraState.Orientation getOrientation();

  /**
   * <code>.Size preview_size = 4;</code>
   * @return Whether the previewSize field is set.
   */
  boolean hasPreviewSize();
  /**
   * <code>.Size preview_size = 4;</code>
   * @return The previewSize.
   */
  eu.long1.nativecamera.proto.Size getPreviewSize();

  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  java.util.List<eu.long1.nativecamera.proto.AspectRatio> 
      getSupportedRatioList();
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  eu.long1.nativecamera.proto.AspectRatio getSupportedRatio(int index);
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  int getSupportedRatioCount();

  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  java.util.List<eu.long1.nativecamera.proto.Range> 
      getSupportedPreviewFpsList();
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  eu.long1.nativecamera.proto.Range getSupportedPreviewFps(int index);
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  int getSupportedPreviewFpsCount();
}
