// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

public interface InitializeCameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitializeCameraResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 textureId = 1;</code>
   * @return The textureId.
   */
  long getTextureId();

  /**
   * <code>.CameraState state = 2;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.CameraState state = 2;</code>
   * @return The state.
   */
  eu.long1.nativecamera.proto.CameraState getState();
}
