// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code InitializeCameraRequest}
 */
public  final class InitializeCameraRequest extends
    com.google.protobuf.GeneratedMessageLite<
        InitializeCameraRequest, InitializeCameraRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:InitializeCameraRequest)
    InitializeCameraRequestOrBuilder {
  private InitializeCameraRequest() {
    channelName_ = "";
  }
  public static final int CHANNEL_NAME_FIELD_NUMBER = 1;
  private java.lang.String channelName_;
  /**
   * <code>string channel_name = 1;</code>
   * @return The channelName.
   */
  @java.lang.Override
  public java.lang.String getChannelName() {
    return channelName_;
  }
  /**
   * <code>string channel_name = 1;</code>
   * @return The bytes for channelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(channelName_);
  }
  /**
   * <code>string channel_name = 1;</code>
   * @param value The channelName to set.
   */
  private void setChannelName(
      java.lang.String value) {
    value.getClass();
  
    channelName_ = value;
  }
  /**
   * <code>string channel_name = 1;</code>
   */
  private void clearChannelName() {
    
    channelName_ = getDefaultInstance().getChannelName();
  }
  /**
   * <code>string channel_name = 1;</code>
   * @param value The bytes for channelName to set.
   */
  private void setChannelNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    channelName_ = value.toStringUtf8();
    
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private eu.long1.nativecamera.proto.CameraState state_;
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.Override
  public boolean hasState() {
    return state_ != null;
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState getState() {
    return state_ == null ? eu.long1.nativecamera.proto.CameraState.getDefaultInstance() : state_;
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  private void setState(eu.long1.nativecamera.proto.CameraState value) {
    value.getClass();
  state_ = value;
    
    }
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeState(eu.long1.nativecamera.proto.CameraState value) {
    value.getClass();
  if (state_ != null &&
        state_ != eu.long1.nativecamera.proto.CameraState.getDefaultInstance()) {
      state_ =
        eu.long1.nativecamera.proto.CameraState.newBuilder(state_).mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  private void clearState() {  state_ = null;
    
  }

  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.InitializeCameraRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code InitializeCameraRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.InitializeCameraRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:InitializeCameraRequest)
      eu.long1.nativecamera.proto.InitializeCameraRequestOrBuilder {
    // Construct using eu.long1.nativecamera.proto.InitializeCameraRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string channel_name = 1;</code>
     * @return The channelName.
     */
    @java.lang.Override
    public java.lang.String getChannelName() {
      return instance.getChannelName();
    }
    /**
     * <code>string channel_name = 1;</code>
     * @return The bytes for channelName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      return instance.getChannelNameBytes();
    }
    /**
     * <code>string channel_name = 1;</code>
     * @param value The channelName to set.
     * @return This builder for chaining.
     */
    public Builder setChannelName(
        java.lang.String value) {
      copyOnWrite();
      instance.setChannelName(value);
      return this;
    }
    /**
     * <code>string channel_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelName() {
      copyOnWrite();
      instance.clearChannelName();
      return this;
    }
    /**
     * <code>string channel_name = 1;</code>
     * @param value The bytes for channelName to set.
     * @return This builder for chaining.
     */
    public Builder setChannelNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChannelNameBytes(value);
      return this;
    }

    /**
     * <code>.CameraState state = 2;</code>
     */
    @java.lang.Override
    public boolean hasState() {
      return instance.hasState();
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState getState() {
      return instance.getState();
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder setState(eu.long1.nativecamera.proto.CameraState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
      }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder setState(
        eu.long1.nativecamera.proto.CameraState.Builder builderForValue) {
      copyOnWrite();
      instance.setState(builderForValue.build());
      return this;
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder mergeState(eu.long1.nativecamera.proto.CameraState value) {
      copyOnWrite();
      instance.mergeState(value);
      return this;
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder clearState() {  copyOnWrite();
      instance.clearState();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:InitializeCameraRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.InitializeCameraRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "channelName_",
            "state_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.InitializeCameraRequest> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.InitializeCameraRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.InitializeCameraRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:InitializeCameraRequest)
  private static final eu.long1.nativecamera.proto.InitializeCameraRequest DEFAULT_INSTANCE;
  static {
    InitializeCameraRequest defaultInstance = new InitializeCameraRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InitializeCameraRequest.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.InitializeCameraRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InitializeCameraRequest> PARSER;

  public static com.google.protobuf.Parser<InitializeCameraRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

