// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code InitializeCameraResponse}
 */
public  final class InitializeCameraResponse extends
    com.google.protobuf.GeneratedMessageLite<
        InitializeCameraResponse, InitializeCameraResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:InitializeCameraResponse)
    InitializeCameraResponseOrBuilder {
  private InitializeCameraResponse() {
    supportedRatio_ = emptyProtobufList();
    supportedPreviewFps_ = emptyProtobufList();
  }
  public static final int TEXTUREID_FIELD_NUMBER = 1;
  private long textureId_;
  /**
   * <code>int64 textureId = 1;</code>
   * @return The textureId.
   */
  @java.lang.Override
  public long getTextureId() {
    return textureId_;
  }
  /**
   * <code>int64 textureId = 1;</code>
   * @param value The textureId to set.
   */
  private void setTextureId(long value) {
    
    textureId_ = value;
  }
  /**
   * <code>int64 textureId = 1;</code>
   */
  private void clearTextureId() {
    
    textureId_ = 0L;
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private eu.long1.nativecamera.proto.CameraState state_;
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.Override
  public boolean hasState() {
    return state_ != null;
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState getState() {
    return state_ == null ? eu.long1.nativecamera.proto.CameraState.getDefaultInstance() : state_;
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  private void setState(eu.long1.nativecamera.proto.CameraState value) {
    value.getClass();
  state_ = value;
    
    }
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeState(eu.long1.nativecamera.proto.CameraState value) {
    value.getClass();
  if (state_ != null &&
        state_ != eu.long1.nativecamera.proto.CameraState.getDefaultInstance()) {
      state_ =
        eu.long1.nativecamera.proto.CameraState.newBuilder(state_).mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  private void clearState() {  state_ = null;
    
  }

  public static final int ORIENTATION_FIELD_NUMBER = 3;
  private int orientation_;
  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   * @return The enum numeric value on the wire for orientation.
   */
  @java.lang.Override
  public int getOrientationValue() {
    return orientation_;
  }
  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   * @return The orientation.
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState.Orientation getOrientation() {
    eu.long1.nativecamera.proto.CameraState.Orientation result = eu.long1.nativecamera.proto.CameraState.Orientation.forNumber(orientation_);
    return result == null ? eu.long1.nativecamera.proto.CameraState.Orientation.UNRECOGNIZED : result;
  }
  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   * @param value The enum numeric value on the wire for orientation to set.
   */
  private void setOrientationValue(int value) {
      orientation_ = value;
  }
  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   * @param value The orientation to set.
   */
  private void setOrientation(eu.long1.nativecamera.proto.CameraState.Orientation value) {
    orientation_ = value.getNumber();
    
  }
  /**
   * <code>.CameraState.Orientation orientation = 3;</code>
   */
  private void clearOrientation() {
    
    orientation_ = 0;
  }

  public static final int PREVIEW_SIZE_FIELD_NUMBER = 4;
  private eu.long1.nativecamera.proto.Size previewSize_;
  /**
   * <code>.Size preview_size = 4;</code>
   */
  @java.lang.Override
  public boolean hasPreviewSize() {
    return previewSize_ != null;
  }
  /**
   * <code>.Size preview_size = 4;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.Size getPreviewSize() {
    return previewSize_ == null ? eu.long1.nativecamera.proto.Size.getDefaultInstance() : previewSize_;
  }
  /**
   * <code>.Size preview_size = 4;</code>
   */
  private void setPreviewSize(eu.long1.nativecamera.proto.Size value) {
    value.getClass();
  previewSize_ = value;
    
    }
  /**
   * <code>.Size preview_size = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePreviewSize(eu.long1.nativecamera.proto.Size value) {
    value.getClass();
  if (previewSize_ != null &&
        previewSize_ != eu.long1.nativecamera.proto.Size.getDefaultInstance()) {
      previewSize_ =
        eu.long1.nativecamera.proto.Size.newBuilder(previewSize_).mergeFrom(value).buildPartial();
    } else {
      previewSize_ = value;
    }
    
  }
  /**
   * <code>.Size preview_size = 4;</code>
   */
  private void clearPreviewSize() {  previewSize_ = null;
    
  }

  public static final int SUPPORTED_RATIO_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.AspectRatio> supportedRatio_;
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  @java.lang.Override
  public java.util.List<eu.long1.nativecamera.proto.AspectRatio> getSupportedRatioList() {
    return supportedRatio_;
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  public java.util.List<? extends eu.long1.nativecamera.proto.AspectRatioOrBuilder> 
      getSupportedRatioOrBuilderList() {
    return supportedRatio_;
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  @java.lang.Override
  public int getSupportedRatioCount() {
    return supportedRatio_.size();
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.AspectRatio getSupportedRatio(int index) {
    return supportedRatio_.get(index);
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  public eu.long1.nativecamera.proto.AspectRatioOrBuilder getSupportedRatioOrBuilder(
      int index) {
    return supportedRatio_.get(index);
  }
  private void ensureSupportedRatioIsMutable() {
    com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.AspectRatio> tmp = supportedRatio_;
    if (!tmp.isModifiable()) {
      supportedRatio_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  private void setSupportedRatio(
      int index, eu.long1.nativecamera.proto.AspectRatio value) {
    value.getClass();
  ensureSupportedRatioIsMutable();
    supportedRatio_.set(index, value);
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  private void addSupportedRatio(eu.long1.nativecamera.proto.AspectRatio value) {
    value.getClass();
  ensureSupportedRatioIsMutable();
    supportedRatio_.add(value);
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  private void addSupportedRatio(
      int index, eu.long1.nativecamera.proto.AspectRatio value) {
    value.getClass();
  ensureSupportedRatioIsMutable();
    supportedRatio_.add(index, value);
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  private void addAllSupportedRatio(
      java.lang.Iterable<? extends eu.long1.nativecamera.proto.AspectRatio> values) {
    ensureSupportedRatioIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, supportedRatio_);
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  private void clearSupportedRatio() {
    supportedRatio_ = emptyProtobufList();
  }
  /**
   * <code>repeated .AspectRatio supported_ratio = 5;</code>
   */
  private void removeSupportedRatio(int index) {
    ensureSupportedRatioIsMutable();
    supportedRatio_.remove(index);
  }

  public static final int SUPPORTED_PREVIEW_FPS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.Range> supportedPreviewFps_;
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  @java.lang.Override
  public java.util.List<eu.long1.nativecamera.proto.Range> getSupportedPreviewFpsList() {
    return supportedPreviewFps_;
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  public java.util.List<? extends eu.long1.nativecamera.proto.RangeOrBuilder> 
      getSupportedPreviewFpsOrBuilderList() {
    return supportedPreviewFps_;
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  @java.lang.Override
  public int getSupportedPreviewFpsCount() {
    return supportedPreviewFps_.size();
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.Range getSupportedPreviewFps(int index) {
    return supportedPreviewFps_.get(index);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  public eu.long1.nativecamera.proto.RangeOrBuilder getSupportedPreviewFpsOrBuilder(
      int index) {
    return supportedPreviewFps_.get(index);
  }
  private void ensureSupportedPreviewFpsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.Range> tmp = supportedPreviewFps_;
    if (!tmp.isModifiable()) {
      supportedPreviewFps_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  private void setSupportedPreviewFps(
      int index, eu.long1.nativecamera.proto.Range value) {
    value.getClass();
  ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.set(index, value);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  private void addSupportedPreviewFps(eu.long1.nativecamera.proto.Range value) {
    value.getClass();
  ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.add(value);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  private void addSupportedPreviewFps(
      int index, eu.long1.nativecamera.proto.Range value) {
    value.getClass();
  ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.add(index, value);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  private void addAllSupportedPreviewFps(
      java.lang.Iterable<? extends eu.long1.nativecamera.proto.Range> values) {
    ensureSupportedPreviewFpsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, supportedPreviewFps_);
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  private void clearSupportedPreviewFps() {
    supportedPreviewFps_ = emptyProtobufList();
  }
  /**
   * <code>repeated .Range supported_preview_fps = 6;</code>
   */
  private void removeSupportedPreviewFps(int index) {
    ensureSupportedPreviewFpsIsMutable();
    supportedPreviewFps_.remove(index);
  }

  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.InitializeCameraResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code InitializeCameraResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.InitializeCameraResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:InitializeCameraResponse)
      eu.long1.nativecamera.proto.InitializeCameraResponseOrBuilder {
    // Construct using eu.long1.nativecamera.proto.InitializeCameraResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 textureId = 1;</code>
     * @return The textureId.
     */
    @java.lang.Override
    public long getTextureId() {
      return instance.getTextureId();
    }
    /**
     * <code>int64 textureId = 1;</code>
     * @param value The textureId to set.
     * @return This builder for chaining.
     */
    public Builder setTextureId(long value) {
      copyOnWrite();
      instance.setTextureId(value);
      return this;
    }
    /**
     * <code>int64 textureId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextureId() {
      copyOnWrite();
      instance.clearTextureId();
      return this;
    }

    /**
     * <code>.CameraState state = 2;</code>
     */
    @java.lang.Override
    public boolean hasState() {
      return instance.hasState();
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState getState() {
      return instance.getState();
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder setState(eu.long1.nativecamera.proto.CameraState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
      }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder setState(
        eu.long1.nativecamera.proto.CameraState.Builder builderForValue) {
      copyOnWrite();
      instance.setState(builderForValue.build());
      return this;
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder mergeState(eu.long1.nativecamera.proto.CameraState value) {
      copyOnWrite();
      instance.mergeState(value);
      return this;
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder clearState() {  copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <code>.CameraState.Orientation orientation = 3;</code>
     * @return The enum numeric value on the wire for orientation.
     */
    @java.lang.Override
    public int getOrientationValue() {
      return instance.getOrientationValue();
    }
    /**
     * <code>.CameraState.Orientation orientation = 3;</code>
     * @param value The orientation to set.
     * @return This builder for chaining.
     */
    public Builder setOrientationValue(int value) {
      copyOnWrite();
      instance.setOrientationValue(value);
      return this;
    }
    /**
     * <code>.CameraState.Orientation orientation = 3;</code>
     * @return The orientation.
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState.Orientation getOrientation() {
      return instance.getOrientation();
    }
    /**
     * <code>.CameraState.Orientation orientation = 3;</code>
     * @param value The enum numeric value on the wire for orientation to set.
     * @return This builder for chaining.
     */
    public Builder setOrientation(eu.long1.nativecamera.proto.CameraState.Orientation value) {
      copyOnWrite();
      instance.setOrientation(value);
      return this;
    }
    /**
     * <code>.CameraState.Orientation orientation = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrientation() {
      copyOnWrite();
      instance.clearOrientation();
      return this;
    }

    /**
     * <code>.Size preview_size = 4;</code>
     */
    @java.lang.Override
    public boolean hasPreviewSize() {
      return instance.hasPreviewSize();
    }
    /**
     * <code>.Size preview_size = 4;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.Size getPreviewSize() {
      return instance.getPreviewSize();
    }
    /**
     * <code>.Size preview_size = 4;</code>
     */
    public Builder setPreviewSize(eu.long1.nativecamera.proto.Size value) {
      copyOnWrite();
      instance.setPreviewSize(value);
      return this;
      }
    /**
     * <code>.Size preview_size = 4;</code>
     */
    public Builder setPreviewSize(
        eu.long1.nativecamera.proto.Size.Builder builderForValue) {
      copyOnWrite();
      instance.setPreviewSize(builderForValue.build());
      return this;
    }
    /**
     * <code>.Size preview_size = 4;</code>
     */
    public Builder mergePreviewSize(eu.long1.nativecamera.proto.Size value) {
      copyOnWrite();
      instance.mergePreviewSize(value);
      return this;
    }
    /**
     * <code>.Size preview_size = 4;</code>
     */
    public Builder clearPreviewSize() {  copyOnWrite();
      instance.clearPreviewSize();
      return this;
    }

    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    @java.lang.Override
    public java.util.List<eu.long1.nativecamera.proto.AspectRatio> getSupportedRatioList() {
      return java.util.Collections.unmodifiableList(
          instance.getSupportedRatioList());
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    @java.lang.Override
    public int getSupportedRatioCount() {
      return instance.getSupportedRatioCount();
    }/**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.AspectRatio getSupportedRatio(int index) {
      return instance.getSupportedRatio(index);
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder setSupportedRatio(
        int index, eu.long1.nativecamera.proto.AspectRatio value) {
      copyOnWrite();
      instance.setSupportedRatio(index, value);
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder setSupportedRatio(
        int index, eu.long1.nativecamera.proto.AspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.setSupportedRatio(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder addSupportedRatio(eu.long1.nativecamera.proto.AspectRatio value) {
      copyOnWrite();
      instance.addSupportedRatio(value);
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder addSupportedRatio(
        int index, eu.long1.nativecamera.proto.AspectRatio value) {
      copyOnWrite();
      instance.addSupportedRatio(index, value);
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder addSupportedRatio(
        eu.long1.nativecamera.proto.AspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedRatio(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder addSupportedRatio(
        int index, eu.long1.nativecamera.proto.AspectRatio.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedRatio(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder addAllSupportedRatio(
        java.lang.Iterable<? extends eu.long1.nativecamera.proto.AspectRatio> values) {
      copyOnWrite();
      instance.addAllSupportedRatio(values);
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder clearSupportedRatio() {
      copyOnWrite();
      instance.clearSupportedRatio();
      return this;
    }
    /**
     * <code>repeated .AspectRatio supported_ratio = 5;</code>
     */
    public Builder removeSupportedRatio(int index) {
      copyOnWrite();
      instance.removeSupportedRatio(index);
      return this;
    }

    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    @java.lang.Override
    public java.util.List<eu.long1.nativecamera.proto.Range> getSupportedPreviewFpsList() {
      return java.util.Collections.unmodifiableList(
          instance.getSupportedPreviewFpsList());
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    @java.lang.Override
    public int getSupportedPreviewFpsCount() {
      return instance.getSupportedPreviewFpsCount();
    }/**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.Range getSupportedPreviewFps(int index) {
      return instance.getSupportedPreviewFps(index);
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder setSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range value) {
      copyOnWrite();
      instance.setSupportedPreviewFps(index, value);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder setSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range.Builder builderForValue) {
      copyOnWrite();
      instance.setSupportedPreviewFps(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder addSupportedPreviewFps(eu.long1.nativecamera.proto.Range value) {
      copyOnWrite();
      instance.addSupportedPreviewFps(value);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder addSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range value) {
      copyOnWrite();
      instance.addSupportedPreviewFps(index, value);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder addSupportedPreviewFps(
        eu.long1.nativecamera.proto.Range.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedPreviewFps(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder addSupportedPreviewFps(
        int index, eu.long1.nativecamera.proto.Range.Builder builderForValue) {
      copyOnWrite();
      instance.addSupportedPreviewFps(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder addAllSupportedPreviewFps(
        java.lang.Iterable<? extends eu.long1.nativecamera.proto.Range> values) {
      copyOnWrite();
      instance.addAllSupportedPreviewFps(values);
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder clearSupportedPreviewFps() {
      copyOnWrite();
      instance.clearSupportedPreviewFps();
      return this;
    }
    /**
     * <code>repeated .Range supported_preview_fps = 6;</code>
     */
    public Builder removeSupportedPreviewFps(int index) {
      copyOnWrite();
      instance.removeSupportedPreviewFps(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:InitializeCameraResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.InitializeCameraResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "textureId_",
            "state_",
            "orientation_",
            "previewSize_",
            "supportedRatio_",
            eu.long1.nativecamera.proto.AspectRatio.class,
            "supportedPreviewFps_",
            eu.long1.nativecamera.proto.Range.class,
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0002\u0000\u0001\u0002\u0002\t" +
              "\u0003\f\u0004\t\u0005\u001b\u0006\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.InitializeCameraResponse> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.InitializeCameraResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.InitializeCameraResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:InitializeCameraResponse)
  private static final eu.long1.nativecamera.proto.InitializeCameraResponse DEFAULT_INSTANCE;
  static {
    InitializeCameraResponse defaultInstance = new InitializeCameraResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InitializeCameraResponse.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.InitializeCameraResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InitializeCameraResponse> PARSER;

  public static com.google.protobuf.Parser<InitializeCameraResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

