// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

public interface InitializeCameraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitializeCameraRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string channel_name = 1;</code>
   * @return The channelName.
   */
  java.lang.String getChannelName();
  /**
   * <code>string channel_name = 1;</code>
   * @return The bytes for channelName.
   */
  com.google.protobuf.ByteString
      getChannelNameBytes();

  /**
   * <code>.CameraState state = 2;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.CameraState state = 2;</code>
   * @return The state.
   */
  eu.long1.nativecamera.proto.CameraState getState();
}
