// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code InitializeCameraResponse}
 */
public  final class InitializeCameraResponse extends
    com.google.protobuf.GeneratedMessageLite<
        InitializeCameraResponse, InitializeCameraResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:InitializeCameraResponse)
    InitializeCameraResponseOrBuilder {
  private InitializeCameraResponse() {
  }
  public static final int TEXTUREID_FIELD_NUMBER = 1;
  private long textureId_;
  /**
   * <code>int64 textureId = 1;</code>
   * @return The textureId.
   */
  @java.lang.Override
  public long getTextureId() {
    return textureId_;
  }
  /**
   * <code>int64 textureId = 1;</code>
   * @param value The textureId to set.
   */
  private void setTextureId(long value) {
    
    textureId_ = value;
  }
  /**
   * <code>int64 textureId = 1;</code>
   */
  private void clearTextureId() {
    
    textureId_ = 0L;
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private eu.long1.nativecamera.proto.CameraState state_;
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.Override
  public boolean hasState() {
    return state_ != null;
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraState getState() {
    return state_ == null ? eu.long1.nativecamera.proto.CameraState.getDefaultInstance() : state_;
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  private void setState(eu.long1.nativecamera.proto.CameraState value) {
    value.getClass();
  state_ = value;
    
    }
  /**
   * <code>.CameraState state = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeState(eu.long1.nativecamera.proto.CameraState value) {
    value.getClass();
  if (state_ != null &&
        state_ != eu.long1.nativecamera.proto.CameraState.getDefaultInstance()) {
      state_ =
        eu.long1.nativecamera.proto.CameraState.newBuilder(state_).mergeFrom(value).buildPartial();
    } else {
      state_ = value;
    }
    
  }
  /**
   * <code>.CameraState state = 2;</code>
   */
  private void clearState() {  state_ = null;
    
  }

  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.InitializeCameraResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.InitializeCameraResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code InitializeCameraResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.InitializeCameraResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:InitializeCameraResponse)
      eu.long1.nativecamera.proto.InitializeCameraResponseOrBuilder {
    // Construct using eu.long1.nativecamera.proto.InitializeCameraResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 textureId = 1;</code>
     * @return The textureId.
     */
    @java.lang.Override
    public long getTextureId() {
      return instance.getTextureId();
    }
    /**
     * <code>int64 textureId = 1;</code>
     * @param value The textureId to set.
     * @return This builder for chaining.
     */
    public Builder setTextureId(long value) {
      copyOnWrite();
      instance.setTextureId(value);
      return this;
    }
    /**
     * <code>int64 textureId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextureId() {
      copyOnWrite();
      instance.clearTextureId();
      return this;
    }

    /**
     * <code>.CameraState state = 2;</code>
     */
    @java.lang.Override
    public boolean hasState() {
      return instance.hasState();
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraState getState() {
      return instance.getState();
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder setState(eu.long1.nativecamera.proto.CameraState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
      }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder setState(
        eu.long1.nativecamera.proto.CameraState.Builder builderForValue) {
      copyOnWrite();
      instance.setState(builderForValue.build());
      return this;
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder mergeState(eu.long1.nativecamera.proto.CameraState value) {
      copyOnWrite();
      instance.mergeState(value);
      return this;
    }
    /**
     * <code>.CameraState state = 2;</code>
     */
    public Builder clearState() {  copyOnWrite();
      instance.clearState();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:InitializeCameraResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.InitializeCameraResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "textureId_",
            "state_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.InitializeCameraResponse> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.InitializeCameraResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.InitializeCameraResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:InitializeCameraResponse)
  private static final eu.long1.nativecamera.proto.InitializeCameraResponse DEFAULT_INSTANCE;
  static {
    InitializeCameraResponse defaultInstance = new InitializeCameraResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InitializeCameraResponse.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.InitializeCameraResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InitializeCameraResponse> PARSER;

  public static com.google.protobuf.Parser<InitializeCameraResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

