// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

public interface ListCamerasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListCamerasResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  java.util.List<eu.long1.nativecamera.proto.CameraInfo> 
      getCamerasList();
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  eu.long1.nativecamera.proto.CameraInfo getCameras(int index);
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  int getCamerasCount();
}
