// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code ListCamerasResponse}
 */
public  final class ListCamerasResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListCamerasResponse, ListCamerasResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:ListCamerasResponse)
    ListCamerasResponseOrBuilder {
  private ListCamerasResponse() {
    cameras_ = emptyProtobufList();
  }
  public static final int CAMERAS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.CameraInfo> cameras_;
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  @java.lang.Override
  public java.util.List<eu.long1.nativecamera.proto.CameraInfo> getCamerasList() {
    return cameras_;
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  public java.util.List<? extends eu.long1.nativecamera.proto.CameraInfoOrBuilder> 
      getCamerasOrBuilderList() {
    return cameras_;
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  @java.lang.Override
  public int getCamerasCount() {
    return cameras_.size();
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  @java.lang.Override
  public eu.long1.nativecamera.proto.CameraInfo getCameras(int index) {
    return cameras_.get(index);
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  public eu.long1.nativecamera.proto.CameraInfoOrBuilder getCamerasOrBuilder(
      int index) {
    return cameras_.get(index);
  }
  private void ensureCamerasIsMutable() {
    com.google.protobuf.Internal.ProtobufList<eu.long1.nativecamera.proto.CameraInfo> tmp = cameras_;
    if (!tmp.isModifiable()) {
      cameras_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  private void setCameras(
      int index, eu.long1.nativecamera.proto.CameraInfo value) {
    value.getClass();
  ensureCamerasIsMutable();
    cameras_.set(index, value);
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  private void addCameras(eu.long1.nativecamera.proto.CameraInfo value) {
    value.getClass();
  ensureCamerasIsMutable();
    cameras_.add(value);
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  private void addCameras(
      int index, eu.long1.nativecamera.proto.CameraInfo value) {
    value.getClass();
  ensureCamerasIsMutable();
    cameras_.add(index, value);
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  private void addAllCameras(
      java.lang.Iterable<? extends eu.long1.nativecamera.proto.CameraInfo> values) {
    ensureCamerasIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, cameras_);
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  private void clearCameras() {
    cameras_ = emptyProtobufList();
  }
  /**
   * <code>repeated .CameraInfo cameras = 1;</code>
   */
  private void removeCameras(int index) {
    ensureCamerasIsMutable();
    cameras_.remove(index);
  }

  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.ListCamerasResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.ListCamerasResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ListCamerasResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.ListCamerasResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:ListCamerasResponse)
      eu.long1.nativecamera.proto.ListCamerasResponseOrBuilder {
    // Construct using eu.long1.nativecamera.proto.ListCamerasResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    @java.lang.Override
    public java.util.List<eu.long1.nativecamera.proto.CameraInfo> getCamerasList() {
      return java.util.Collections.unmodifiableList(
          instance.getCamerasList());
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    @java.lang.Override
    public int getCamerasCount() {
      return instance.getCamerasCount();
    }/**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    @java.lang.Override
    public eu.long1.nativecamera.proto.CameraInfo getCameras(int index) {
      return instance.getCameras(index);
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder setCameras(
        int index, eu.long1.nativecamera.proto.CameraInfo value) {
      copyOnWrite();
      instance.setCameras(index, value);
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder setCameras(
        int index, eu.long1.nativecamera.proto.CameraInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setCameras(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder addCameras(eu.long1.nativecamera.proto.CameraInfo value) {
      copyOnWrite();
      instance.addCameras(value);
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder addCameras(
        int index, eu.long1.nativecamera.proto.CameraInfo value) {
      copyOnWrite();
      instance.addCameras(index, value);
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder addCameras(
        eu.long1.nativecamera.proto.CameraInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addCameras(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder addCameras(
        int index, eu.long1.nativecamera.proto.CameraInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addCameras(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder addAllCameras(
        java.lang.Iterable<? extends eu.long1.nativecamera.proto.CameraInfo> values) {
      copyOnWrite();
      instance.addAllCameras(values);
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder clearCameras() {
      copyOnWrite();
      instance.clearCameras();
      return this;
    }
    /**
     * <code>repeated .CameraInfo cameras = 1;</code>
     */
    public Builder removeCameras(int index) {
      copyOnWrite();
      instance.removeCameras(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ListCamerasResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.ListCamerasResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "cameras_",
            eu.long1.nativecamera.proto.CameraInfo.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.ListCamerasResponse> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.ListCamerasResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.ListCamerasResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ListCamerasResponse)
  private static final eu.long1.nativecamera.proto.ListCamerasResponse DEFAULT_INSTANCE;
  static {
    ListCamerasResponse defaultInstance = new ListCamerasResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListCamerasResponse.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.ListCamerasResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListCamerasResponse> PARSER;

  public static com.google.protobuf.Parser<ListCamerasResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

