// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Point)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();
}
