// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

/**
 * Protobuf type {@code Range}
 */
public  final class Range extends
    com.google.protobuf.GeneratedMessageLite<
        Range, Range.Builder> implements
    // @@protoc_insertion_point(message_implements:Range)
    RangeOrBuilder {
  private Range() {
  }
  public static final int MIN_FIELD_NUMBER = 1;
  private int min_;
  /**
   * <code>int32 min = 1;</code>
   * @return The min.
   */
  @java.lang.Override
  public int getMin() {
    return min_;
  }
  /**
   * <code>int32 min = 1;</code>
   * @param value The min to set.
   */
  private void setMin(int value) {
    
    min_ = value;
  }
  /**
   * <code>int32 min = 1;</code>
   */
  private void clearMin() {
    
    min_ = 0;
  }

  public static final int MAX_FIELD_NUMBER = 2;
  private int max_;
  /**
   * <code>int32 max = 2;</code>
   * @return The max.
   */
  @java.lang.Override
  public int getMax() {
    return max_;
  }
  /**
   * <code>int32 max = 2;</code>
   * @param value The max to set.
   */
  private void setMax(int value) {
    
    max_ = value;
  }
  /**
   * <code>int32 max = 2;</code>
   */
  private void clearMax() {
    
    max_ = 0;
  }

  public static eu.long1.nativecamera.proto.Range parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.Range parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.Range parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static eu.long1.nativecamera.proto.Range parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(eu.long1.nativecamera.proto.Range prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code Range}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        eu.long1.nativecamera.proto.Range, Builder> implements
      // @@protoc_insertion_point(builder_implements:Range)
      eu.long1.nativecamera.proto.RangeOrBuilder {
    // Construct using eu.long1.nativecamera.proto.Range.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 min = 1;</code>
     * @return The min.
     */
    @java.lang.Override
    public int getMin() {
      return instance.getMin();
    }
    /**
     * <code>int32 min = 1;</code>
     * @param value The min to set.
     * @return This builder for chaining.
     */
    public Builder setMin(int value) {
      copyOnWrite();
      instance.setMin(value);
      return this;
    }
    /**
     * <code>int32 min = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMin() {
      copyOnWrite();
      instance.clearMin();
      return this;
    }

    /**
     * <code>int32 max = 2;</code>
     * @return The max.
     */
    @java.lang.Override
    public int getMax() {
      return instance.getMax();
    }
    /**
     * <code>int32 max = 2;</code>
     * @param value The max to set.
     * @return This builder for chaining.
     */
    public Builder setMax(int value) {
      copyOnWrite();
      instance.setMax(value);
      return this;
    }
    /**
     * <code>int32 max = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMax() {
      copyOnWrite();
      instance.clearMax();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Range)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new eu.long1.nativecamera.proto.Range();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "min_",
            "max_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<eu.long1.nativecamera.proto.Range> parser = PARSER;
        if (parser == null) {
          synchronized (eu.long1.nativecamera.proto.Range.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<eu.long1.nativecamera.proto.Range>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:Range)
  private static final eu.long1.nativecamera.proto.Range DEFAULT_INSTANCE;
  static {
    Range defaultInstance = new Range();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Range.class, defaultInstance);
  }

  public static eu.long1.nativecamera.proto.Range getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Range> PARSER;

  public static com.google.protobuf.Parser<Range> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

