// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

public interface RangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Range)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 min = 1;</code>
   * @return The min.
   */
  int getMin();

  /**
   * <code>int32 max = 2;</code>
   * @return The max.
   */
  int getMax();
}
