// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package eu.long1.nativecamera.proto;

public interface SizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Size)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 width = 1;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 2;</code>
   * @return The height.
   */
  int getHeight();
}
