// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

public interface TakePictureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TakePictureResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.CameraState.Orientation device_orientation = 1;</code>
   * @return The enum numeric value on the wire for deviceOrientation.
   */
  int getDeviceOrientationValue();
  /**
   * <code>.CameraState.Orientation device_orientation = 1;</code>
   * @return The deviceOrientation.
   */
  eu.long1.nativecamera.proto.CameraState.Orientation getDeviceOrientation();

  /**
   * <code>.CameraState.Orientation picture_orientation = 2;</code>
   * @return The enum numeric value on the wire for pictureOrientation.
   */
  int getPictureOrientationValue();
  /**
   * <code>.CameraState.Orientation picture_orientation = 2;</code>
   * @return The pictureOrientation.
   */
  eu.long1.nativecamera.proto.CameraState.Orientation getPictureOrientation();

  /**
   * <code>map&lt;string, string&gt; exif = 3;</code>
   */
  int getExifCount();
  /**
   * <code>map&lt;string, string&gt; exif = 3;</code>
   */
  boolean containsExif(
      java.lang.String key);
  /**
   * Use {@link #getExifMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExif();
  /**
   * <code>map&lt;string, string&gt; exif = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExifMap();
  /**
   * <code>map&lt;string, string&gt; exif = 3;</code>
   */

  java.lang.String getExifOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; exif = 3;</code>
   */

  java.lang.String getExifOrThrow(
      java.lang.String key);

  /**
   * <code>int32 width = 4;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 5;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>string uri = 6;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <code>string uri = 6;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <code>bytes data = 7;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
