// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: native_camera.proto

package eu.long1.nativecamera.proto;

public interface TakePictureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TakePictureRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>map&lt;string, string&gt; exif = 2;</code>
   */
  int getExifCount();
  /**
   * <code>map&lt;string, string&gt; exif = 2;</code>
   */
  boolean containsExif(
      java.lang.String key);
  /**
   * Use {@link #getExifMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExif();
  /**
   * <code>map&lt;string, string&gt; exif = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExifMap();
  /**
   * <code>map&lt;string, string&gt; exif = 2;</code>
   */

  java.lang.String getExifOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; exif = 2;</code>
   */

  java.lang.String getExifOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Should write exif to file
   * </pre>
   *
   * <code>bool write_exif = 3;</code>
   * @return The writeExif.
   */
  boolean getWriteExif();

  /**
   * <pre>
   * Value between 0-1
   * </pre>
   *
   * <code>double quality = 4;</code>
   * @return The quality.
   */
  double getQuality();

  /**
   * <code>bool pause_after_capture = 5;</code>
   * @return The pauseAfterCapture.
   */
  boolean getPauseAfterCapture();

  /**
   * <pre>
   * only used on Android
   * </pre>
   *
   * <code>bool fix_orientation = 6;</code>
   * @return The fixOrientation.
   */
  boolean getFixOrientation();

  /**
   * <pre>
   * only used on iOS
   * </pre>
   *
   * <code>bool force_up_orientation = 7;</code>
   * @return The forceUpOrientation.
   */
  boolean getForceUpOrientation();

  /**
   * <code>int32 width = 8;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>bool mirror_image = 9;</code>
   * @return The mirrorImage.
   */
  boolean getMirrorImage();

  /**
   * <code>bool do_not_save = 10;</code>
   * @return The doNotSave.
   */
  boolean getDoNotSave();

  /**
   * <code>bool return_bytes = 11;</code>
   * @return The returnBytes.
   */
  boolean getReturnBytes();

  /**
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @return The enum numeric value on the wire for orientation.
   */
  int getOrientationValue();
  /**
   * <code>.CameraState.Orientation orientation = 12;</code>
   * @return The orientation.
   */
  eu.long1.nativecamera.proto.CameraState.Orientation getOrientation();
}
